### PR TITLE
Don't require birth year-month on cases

### LINKED ISSUE #2794: Supervisor can't edit case with missing birth year-month
### Impacted User Types
 - supervisors

### Environment
staging https://casa-r4g-staging.herokuapp.com/casa_cases/485

### Current Behavior
As a supervisor, try to edit a case without birth year/month
It is impossible and you can't edit birth year/month (not visible)
Screen Shot 2021-10-15 at 8 38 06 PM

### Expected Behavior
????

### How to Replicate
ex: 
1. - Log into staging as an admin or supervisor.
2. - Click on "Generate Reports" in the left sidebar menu.
3. - Filter by a volunteer who has logged at least one case contact.
4. - Click "Generate report" at the bottom of the page.

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by valeriecodes**
### What github issue is this PR for, if any?
Resolves #2794

### What changed, and why?
This makes the "birth month year youth" field not required on Casa cases. It was causing this bug: https://github.com/rubyforgood/casa/issues/2794 and also doesn't seem to always render on the form? https://github.com/rubyforgood/casa/blob/main/app/views/casa_cases/_form.html.erb#L21-L36

But I may have misinterpreted, happy to make changes if this doesn't feel like the right solution :)

### How will this affect user permissions?
- Volunteer permissions: No change
- Supervisor permissions: No change
- Admin permissions: No change

### How is this tested? (please write tests!) 💖💪
Unit tests edited, tried saving case in dev environment without the field.

### Screenshots please :)
N/A

### Feelings gif (optional)
happy

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by valeriecodes** [comment]
Not sure why lint is failing here, all the flagged files are ones I haven't touched and it seems fine when I run locally.

**Review by compwron — CHANGES_REQUESTED** [review]
Let me think about this one for a bit- we *do* want this everywhere, but first we need to do some refactoring around the duplicate field

**Comment by compwron** [comment]
I have not forgotten this, I am just struggling with it- we don't want to relax this validation, we want all our data to magically become valid...

**Comment by compwron** [comment]
Closing for now because admin can set birth but supervisor can't and we don't want to build a custom error. Bummer. Sorry for the confusion.

**Pull request closed without merging**
