### PR TITLE
Case#1197 add friendlier warning box admin disables case

### LINKED ISSUE #1197: Friendlier warning box when Admin disables a CASA Case
**What type of user is this for? volunteer/supervisor/admin/all**
Admin (only admins have permission to deactivate a case)

**Description**
Right now, we're using a basic browser warning when an Admin clicks "Deactivate CASA Case". We want a prettier, more user-friendly dialogue box with customized button text. 

**Acceptance Criteria**
[] Clicking on "Deactivate CASA Case" triggers a dialogue reading: Deactivating a CASA Case will unassign any volunteers currently assigned to this case. Are you sure you'd like to continue? and two buttons: "Yes, deactivate" and "No, go back"
[] Clicking "Yes, deactivate" deactivates casa_case 
[] Clicking "No, go back" closes dialogue box.

**Screenshots of current behavior, if any**
Current warning:
Screen Shot 2020-10-25 at 7 57 46 PM

### PR DESCRIPTION
**Pull request by Math-O5**
### What github issue is this PR for, if any?
Resolves #1197

### What changed, and why?
Only visual changes
Add dependency of sweet alert 2 on packeage.json
Apply warning box of sweet alert fire when disable case

### How will this affect user permissions?
- Volunteer permissions: none
- Supervisor permissions: none
- Admin permissions: none

### How is this tested? (please write tests!) 💖💪
Run default tests only

### Screenshots please :)
cana_new_popup
success

### Feelings gif (optional)
I'm starting contributing, take easy on me! haha

### CODE REVIEW

**Comment by Math-O5** [comment]
What is this peding of The Travis Ci Build in progress?

**Comment by compwron** [comment]
> What is this peding of The Travis Ci Build in progress?

@Math-O5 The Travis CI build runs all our tests with your new code. Right now it's broken because there are tests for the alert that you changed! Please update the tests to work with your cool new code :) 

You can run them on your local machine by running 
`rspec ./spec/system/admin_edits_a_case_spec.rb`

You can see all the details at https://travis-ci.org/github/rubyforgood/casa/builds/739758181 (Click "Details" next to the red X line) 
Screen Shot 2020-10-28 at 6 59 55 PM
Screen Shot 2020-10-28 at 6 59 20 PM

**Review by compwron — APPROVED** [review]
Very nice!

**Comment by compwron** [comment]
You are invited to the CASA asynchronous retrospective-and-futurespective! Please take a look at https://bit.ly/casaretro (no login required) and add at least one note! Even if it's just "I was here and you are cool" or "omg y'all why do you keep messaging me" we want to hear it. <3
Next week Wednesday 18 November @ 6pm Pacific time we will Zoom about the board and talk about themes and takeaways. (Zoom link in our calendar at http://bit.ly/casacal or slack #casa channel https://rubyforgood.herokuapp.com/ )
Please ESPECIALLY add lots of notes if you won't be able to make it on Wednesday to talk!
* Note: the board will be monitored for spam; message me or any team lead if you see a problem
https://bit.ly/casaretro

**Pull request merged**
