### PR TITLE
WIP for issue 4666

### LINKED ISSUE #4666: Ability to lock cases for case contacts
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
 - Remove autosaving of checked cases from the case contact form autosaver
 - For each casa case listed at the top of the new case contact form, put a lock button on the right
 - The lock button will
    - have an unlocked icon by default
    - toggle between a locked and unlocked icon when clicked
    - disable the checkbox left of it when in locked mode
    - make the checkbox checked in locked mode
 - The locked state will not change until the user toggles the lock
 - Write System Tests

Kind of like this but make the buttons line up
image

**Screenshots of current behavior**  
image

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by dominiclizarraga**
### What github issue is this PR for, if any?
Resolves #4666 

### What changed, and why?

The autosave for contact cases was removed and a new icon was added. 

### How will this affect user permissions?
- Volunteer permissions: 
- Supervisor permissions:
- Admin permissions:

### How is this tested? (please write tests!) 💖💪

I want feedback on this solution, then I'll write testing.

### Screenshots please :)

https://user-images.githubusercontent.com/70678718/231666514-cbff7c74-3540-441f-b03d-5c71164568ab.mov

### CODE REVIEW

**Comment by FireLemons** [comment]
you gotta get your linter checks to pass

**Comment by FireLemons** [comment]
Could you update your branch with the latest changes from main so that the new theme changes are applied? It would make it easier to QA.

**Comment by FireLemons** [comment]
If the checkboxes are disabled the cases they represent can't be passed to the controller. We need them to look and act disabled but still work.

**Comment by dominiclizarraga** [comment]
Sure Shen, let me work on that.

**Comment by dominiclizarraga** [comment]
@FireLemons  let me know if the behaviour is the expected: "checkboxes look and act as disabled but still work"

- [ ] linter checks

- [ ] rebase main

- [ ] tests

**Comment by FireLemons** [comment]
image
looks like merging the new theme removed the id from the submit button

**Comment by FireLemons** [comment]
can you run `yarn lint:fix`

**Comment by FireLemons** [comment]
could you move the locks to the right side of the casa case number? so they all have the same horizontal postition

**Comment by FireLemons** [comment]
clicking the locks seem to do nothing now

**Comment by dominiclizarraga** [comment]
@FireLemons sorry for being late. Please see the PR #4814

**Pull request closed without merging**
