### PR TITLE
Removed other contact type from case_contacts

### LINKED ISSUE #89: Remove `other` from case_contact contact_type dropdown
Part of epic #3 (volunteer dashboard)

`other` should be removed from the dropdown menu under `contact_type` when creating a new `case_contact`

<a href="https://casa-r4g-staging.herokuapp.com/case_contacts/new">see here for reference on staging</a>

### PR DESCRIPTION
**Pull request by eclectic-coding**
Resolves #89 

### What changed, and why?
- Removed `other` from `CONTACT_TYPES` found in `case_contact` model. 
- Edited Type output to remove string concat for `other_type_text`
- Removed method `use_other_type_test?`
- Updated `db/seeds` to remove `other` field, so model will validate. 

### How will this affect user permissions?

Does not affect permissions

### How is this tested?
This features was not originally tested, so no changes to testing. 

### Outstanding issue
Since I just started volunteering on this project I am not aware of the status of the production database. Because of this I did not create a `db migration` to remove the `other_type_text` field. If you want me to go back and create a migration I can, but if there is existing data in the `other_type_text` column in the production database, it will no longer display in the dashboard. 

thank you for the opportunity to volunteer.

### CODE REVIEW

**Comment by compwron** [comment]
This is great! Thanks :)

**Comment by compwron** [comment]
It looks like the failing test in CI is 
```
 1) volunteer adds a case contact chooses other
     Failure/Error: expect(CaseContact.first.contact_type).to eq 'other'
     
       expected: "other"
            got: "other_family"
     
       (compared using ==)
     # ./spec/features/volunteer_adds_a_case_contact_spec.rb:44:in `block (2 levels) in <top (required)>'
```
I will approve this, feel free to merge when the build passes :)

**Comment by eclectic-coding** [comment]
Do I need to go look at the spec file noted?

**Comment by compwron** [comment]
Very cool! Thanks for the PR ✨👏🏼💖✨

**Pull request merged**
