### PR TITLE
2887 Volunteer Learning Hours

### LINKED ISSUE #2887: Add a [Learning Hours / Continuing Education / Training] Tab to the Volunteer Sidebar
**What type(s) of user does this feature affect?**
 - volunteers

**Description**
Currently we have no way for volunteers to track their Learning Hours. We would like to add a new tab to the Volunteers Sidebar labelled Learning Hours. This tab should contain a page with a button that is labelled New Learning Hours. This button should lead to a page that is similar to a New Case Contact page with:
- a dropdown for the Type of Learning Hours (with options: book, movie, webinar, conference, and other), 
- Duration and Occurred At fields (these should be exactly the same as on the New Case Contact Form),
- and a field labelled Title that allows volunteers to type in the full title of whatever Learning Hours they have just completed. 

Once any learning hours have been submitted, all learning hours should be visible on the Learning Hours landing page under the New Learning Hours button similar to the way Case Contacts are listed on the Case Contacts landing page. 

**Screenshots of current behavior, if any**  
Sidebar where the new tab should be added:
Volunteer Sidebar

These fields should be lifted from the case contact page and reused: 
Duration and Occured at Fields

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by caitmich**
### What github issue is this PR for, if any?
Resolves #2887

### What changed, and why?
- `Learning Hours` tab in sidebar for volunteer accounts
- `learning_hours` routes, model, controller, views
- `/volunteers/:id/learning_hours` Learning Hours index (landing) page shows a volunteer's documented learning hours
- New Learning Hours button renders form where volunteer can add learning hours
- Title, type, occurred at, and duration fields included

### How will this affect user permissions?
- Volunteer permissions: 
Volunteers can view, edit and delete their own learning hours entries
- Supervisor permissions: 
 
- Admin permissions:

### How is this tested? (please write tests!) 💖💪
Tested using rspec, and linted. Autocorrectable offenses are corrected

### Screenshots please :)
Sidebar navigation menu
Labels on Title and Type fields
jQuery Date Picker

### CODE REVIEW

**Comment by FireLemons** [comment]
Maybe "add learning hours" or "reocrd learning hours instead"
image

**Comment by FireLemons** [comment]
submitting the form without the required fields throws an uncaught error
image

**Comment by FireLemons** [comment]
Could you move the learning hours type next to a label
image

Similar to this
image

**Comment by FireLemons** [comment]
Could you use JQuery's datepicker for the occurred on field?
image

It looks like this
image

**Comment by caitmich** [comment]
Thanks for your feedback, will make necessary changes!

**Comment by FireLemons** [comment]
For that uncaught exception, on most other pages, we use this error partial to show when field values are invalid.

https://github.com/rubyforgood/casa/blob/72e4620ca7e0f808359c4a3f814edc45a982924a/app/views/casa_cases/_form.html.erb#L4

Looks like this
image

**Comment by compwron** [comment]
How is it going? :)

**Comment by caitmich** [comment]
Good! Just need to get the tests passing and then it’s good to go! (The functionality is working and tested, but the tests don’t like some things)

**Comment by compwron** [comment]
this is exciting and I would like to get it merged :)

**Comment by compwron** [comment]
Docker is sad but I think in an invalid way. Let's merge and see where we get to

**Pull request merged**
