### PR TITLE
Issues/2415 Add Colored Bars to Supervisor's Screen

### LINKED ISSUE #2415: Add Colored Bars to Supervisor's Screen
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
We would like to add colored bars to the chart that tells supervisors about their volunteers. These bars would be black rectangles filled with green to the appropriate percentage to represent how many of each supervisor's volunteers had made contact in the last fourteen days and red in the appropriate percent to represent the volunteers that haven't made case contacts in the last fourteen days. The number of transition aged youth would appear at the end of the bar in parenthesis. Above the top of the list of supervisor's there should be an explanatory version of the bar that's fifty-fifty and has "Have made contact in the last 14 days" in the green section, and "Have not made contact in the last fourteen days" in the red section. Beside this example bar should be "(Transition aged youth)" in black to match the styling of the bars for individual supervisors. 

**Screenshots of current behavior, if any**  
Supervisor Visual Tracking Bar

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

### PR DESCRIPTION
**Pull request by jesselasalle**
### What github issue is this PR for, if any?
Resolves #2415

### What changed, and why?
The three columns representing total volunteers, volunteers without contact in 14 days, and transition aged youth have been replaced with a bar showing how many active and non-attempt volunteers, per the issue.

### How will this affect user permissions?
N/A

### How is this tested? (please write tests!) 💖💪
`spec/views/supervisors/index.html.erb_spec.rb`

### Screenshots please :)
image

### CODE REVIEW

**Comment by compwron** [comment]
:) :) :)

**Comment by compwron** [comment]
Some red specs

```

rspec ./spec/system/supervisors/index_spec.rb:284 # supervisors/index with inactive volunteers assigned count only active volunteers
rspec ./spec/system/supervisors/index_spec.rb:209 # supervisors/index supervisor table filters status when only inactive checked filters the supervisors correctly
rspec ./spec/system/supervisors/index_spec.rb:225 # supervisors/index supervisor table filters status when both checked filters the supervisors correctly
rspec ./spec/system/supervisors/index_spec.rb:193 # supervisors/index supervisor table filters status when only active checked filters the supervisors correctly
```

**Review by compwron — APPROVED** [review]
I love it! Feel free to merge when the build is green

**Comment by jesselasalle** [comment]
Update: failing specs uncovered a bug. Will come back to this when I have some time :)

**Comment by compwron** [comment]
I'm merging on red to show this to stakeholders. will fix soonest.

**Pull request merged**
