### PR TITLE
Add json response for CasaCase actions that hits the database

### PR DESCRIPTION
**Pull request by mauricio-prl**
References https://github.com/rubyforgood/casa/issues/2647

### What changed, and why?

Adding json response for `update`, `deactivate` and `reactivate` of `CasaCaseController`

### How is this tested? (please write tests!) 💖💪

Unit tests for the controller class

### CODE REVIEW

**Comment by m-pereira** [comment]
Those standardrb lint errors is in files that I didn't change

```
        modified:   app/controllers/case_court_reports_controller.rb
        modified:   app/controllers/concerns/accessible.rb
        modified:   app/helpers/template_helper.rb
        modified:   db/migrate/20200329050100_create_casa_cases.rb
        modified:   db/migrate/20200329062155_devise_create_users.rb
        modified:   db/migrate/20200329064203_add_role_to_user.rb
        modified:   db/migrate/20200329071025_change_casa_case_teen_to_required.rb
        modified:   db/migrate/20200329071327_change_casa_case_number_to_required.rb
        modified:   db/migrate/20200329071626_add_unique_index_on_case_case_number.rb
        modified:   db/migrate/20200329074655_create_supervisor_volunteers.rb
        modified:   db/migrate/20200329081206_create_case_assignments.rb
 ```

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
@m-pereira feel free to merge after you fix the merge conflict and lint :)

**Comment by m-pereira** [comment]
> @m-pereira feel free to merge after you fix the merge conflict and lint :)

I think we need to solve those lint issues in another PR, since those files don't interfere here

**Comment by compwron** [comment]
> > @m-pereira feel free to merge after you fix the merge conflict and lint :)
> 
> I think we need to solve those lint issues in another PR, since those files don't interfere here. The conflicts I'll fix that as soon as possible

the lint is fixed in the main branch, if you merge the main branch in then the lint issues should go away. It is ok to ignore them.

**Comment by m-pereira** [comment]
Hey @compwron the conflicts are solved, can you please take a look one more time, and merge it if it's all right? :D

**Review by compwron — APPROVED** [review]

**Pull request merged**
