### PR TITLE
[5042] experiment with pulling docx helpers out in favor of letting a gem do it

### LINKED ISSUE #5042: Pull out docx inspector in favor of a doc gem
**Description**

**Existing gem(s), file(s) needing updating, changing or deleting**
docx is a gem (https://github.com/ruby-docx/docx/tree/master) that helps with reading and parsing word docs. it makes the code a lot slimmer with regards to a helper class that currently exists. exploring pulling that out

**New file(s) needing creating**

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by FeminismIsAwesome**
### What github issue is this PR for, if any?
Resolves #5042 

https://github.com/ruby-docx/docx/pull/137 will make this even simpler once we get that going

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by littleforest** [comment]
Can you check the failing specs?

**Comment by littleforest** [comment]
Can you double check specs again?! Thanks!

**Comment by littleforest** [comment]
@FeminismIsAwesome please lint! I think the spec failure might be flaky.

**Comment by FeminismIsAwesome** [comment]
@littleforest can you give it another look? fixed the tests (that aren't flakes)

**Review by littleforest — APPROVED** [review]
Looks great! Thanks for working on this.

**Pull request merged**
