### PR TITLE
Let Supervisors and Admins Hide Case Contacts Made by Previous Volunteers on a Case

### LINKED ISSUE #3338: Let Supervisors and Admins Hide Case Contacts Made by Previous Volunteers on a Case
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when a case is unassigned from one volunteer and assigned to a new volunteer, the new volunteer can see case contacts made by the old volunteer. We would like supervisors and admins to be able to choose whether new volunteers see old volunteers case contacts. Specifically, we would like to add a action to the Manage Volunteers Table for= volunteers with the status 'Unassigned' or 'Deactivated Volunteer', which is labeled "Hide Case Contacts" and will hide case contacts made by that volunteer from other volunteers assigned to the case. 

**Screenshots of current behavior, if any**  
New Volunteer seeing Old Case Contacts: 
New Volunteer Sees Old Volunteers Case Contacts

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by arthur1041**
### What github issue is this PR for, if any?
Resolves #3338

### What changed, and why?
Supervisors and Admins are now able to choose whether new volunteers see old volunteers' case contacts on a casa case.

### How will this affect user permissions?
- Volunteer permissions: Will only be able to see old case contacts if an admin or supervisor allows it.
- Supervisor permissions: Can define whether volunteers can see old case_contacts or not.
- Admin permissions:

### How is this tested? (please write tests!) 💖💪
There were added system and request tests. Just run rspec.

### Screenshots please :)
Screenshot 2022-06-10 11:57:06

### CODE REVIEW

**Comment by compwron** [comment]
This is looking promising! Please fix the failing tests :)

**Comment by arthur1041** [comment]
@compwron do you have any tips on how to fix this codeclimate error?

**Comment by arthur1041** [comment]
I managed to fix it.

> @compwron do you have any tips on how to fix this codeclimate error?

I managed to fix it.

**Comment by compwron** [comment]
Very cool!

**Review by compwron — APPROVED** [review]
yay tests :)

**Pull request merged**
