### PR TITLE
Move user permission logic from erb into pundit policy files 

### LINKED ISSUE #996: Move user permission logic from erb into pundit policy files
**What type of user is this for? volunteer/supervisor/admin/all**
all

**Description**
Move logic about whether a user is allowed to do something from .erb files into the appropriate pundit policy files
`<% if !current_user.supervisor?` 

Extra credit / stretch goal: write a test that fails when logic like `current_user.casa_admin?`  etc is added to an erb file (the hard part is avoiding false positives...)

### PR DESCRIPTION
**Pull request by Mozart2234**
### What GitHub issue is this PR for if any?
Resolves #996 

### What changed, and why?

I moved all of the permission logic from UI/views into pundit policy files.

### How will this affect user permissions?
- Volunteer permissions: n/a
- Supervisor permissions: n/a
- Admin permissions: n/a

### How is this tested? (please write tests!) 💖💪

- Well, I added new tests in `spec/policies` for check permissions in actions.
- I needed to refactor and fixed some tests because some view does not have a pundit activate.
-  I think to improve organization in some tests using let and before.

### Screenshots, please :)

I'm not changed anything views, only move the logic into pundit policy files.

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
challenge accepted

### CODE REVIEW

**Review by compwron — APPROVED** [review]
This is looking very good! Just one merge conflict to resolve, and the build is being bad - not your fault - I will work on that 😅

**Comment by Mozart2234** [comment]
@compwron Thanks!, Just now I solved this merge conflict and move this permission logic to a new pundit permission.

**Comment by Mozart2234** [comment]
> This is looking very good! Just one merge conflict to resolve, and the build is being bad - not your fault - I will work on that 😅

Oh, I see, but I use the command for passed all tests and we have problems in active pundit, but I did it, jejeje. Thanks for your answer.

**Comment by compwron** [comment]
This build passed- the build just false-fails because of pr autotagging and a flaky test on the integration branch. I will keep an eye on the master build.

**Comment by Mozart2234** [comment]
Hi, why this PR has two reverts? Do I need added other change?

**Comment by compwron** [comment]
@Mozart2234 This PR has a revert and a revert-of-revert because I took the code out of master in case it was related to a problem, and then I put the code back into master after I knew that it was not related to a problem. So the code is merged and you do not need to make a change. :) https://github.com/rubyforgood/casa/pull/1027

**Pull request merged**
