### PR TITLE
Feat/replace old feature flags with flipper

### PR DESCRIPTION
**Pull request by elasticspoon**
https://github.com/rubyforgood/casa/pull/5851 added flipper to the application to do feature flags.

This PR removes our custom hand rolled feature flags and replaces them with flipper. All the related flags are already set in production.

### CODE REVIEW

**Comment by schoork** [comment]
@elasticspoon is this extra auth form expected? How do I get the local username/password?
Screenshot 2024-07-07 at 9 41 49 AM

**Comment by elasticspoon** [comment]
> @elasticspoon is this extra auth form expected? How do I get the local username/password? Screenshot 2024-07-07 at 9 41 49 AM

@schoork  You set user and pass via env vars FLIPPER_USERNAME and FLIPPER_PASSWORD. I'll add defaults. The defaults exist for fresh setups via .env.example but not existing setups.

**Comment by schoork** [comment]
> > @elasticspoon is this extra auth form expected? How do I get the local username/password? Screenshot 2024-07-07 at 9 41 49 AM
> 
> @schoork You set user and pass via env vars FLIPPER_USERNAME and FLIPPER_PASSWORD. I'll add defaults. The defaults exist for fresh setups via .env.example but not existing setups.

Is it expected that you can get into it without logging in as an All CASA Admin?

**Comment by schoork** [comment]
It might be worth adding a note in the readme about how to set a feature in the future in production. Should devs do this via a request or an AfterParty task?

**Review by schoork — APPROVED** [review]

**Comment by elasticspoon** [comment]
> It might be worth adding a note in the readme about how to set a feature in the future in production. Should devs do this via a request or an AfterParty task?

I'll add a page in the wiki I think. 

Auth via devise makes sense, so I made that change.

**Pull request merged**
