### PR TITLE
Fix Contact Type Select Styles Issue #5759

### LINKED ISSUE #5759: Fix Contact Type Select Styles
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

In the contact type selection dropdown when something is being searched for the currently typed in letters get highlighted. 

Image

As you can see the styling is off. Fix the css styling so this issue is no longer occurring.

- [ ] Fix on page `/case_contacts/:id/form/details` in form Select All Contact Types 
- [ ] Fix on page `/casa_cases/new` in form Contact Types

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by logtay**
### What github issue is this PR for, if any?
Resolves #5759 

### What changed, and _why_?
The first letter in the dropdown is now in line with the rest of the word so that options are properly selected. Only the first letter of the searched contact type was getting selected, which would make it difficult for users to read. These changes affect the casa_cases and case_contacts pages

### How is this **tested**? (please write tests!) 💖💪
_Note: if you see a flake in your test build in github actions, please post in slack #casa "Flaky test: <link to failed build>" :) 💪_
_Note: We love [capybara](https://rubydoc.info/github/teamcapybara/capybara) tests! If you are writing both haml/js and ruby, please try to test your work with tests at every level including system tests like https://github.com/rubyforgood/casa/tree/main/spec/system_ 

Changes were only made to CSS, so I did not create any new tests. 

### Screenshots please :)
_Run your local server and take a screenshot of your work! Try to include the URL of the page as well as the contents of the page._ 
Screen Shot 2024-06-10 at 19 28 03
Screen Shot 2024-06-10 at 19 28 47

### Feelings gif (optional)
_What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:_
alt text

### CODE REVIEW

**Review by elasticspoon — CHANGES_REQUESTED** [review]
Thanks for the fix! The styles work great! :slightly_smiling_face: 

The only change I would like to see is to place this behavior in a slightly different place. 

Currently we are using tomselect as a component so ideally we want to be able to reuse it on other pages so we should but the styles somewhere in `/app/assets/stylesheets/shared` to reflect that the styles are not page specific. Maybe similar to how the select2 styles live there. 

Also in that situation we should also use a selector more tailored to the tom-select drop down maybe `.ts-dropdown [data-selectable] .highlight` which is what tomselect already uses.

**Comment by logtay** [comment]
Thank you for the feedback! I will make those changes

**Review by elasticspoon — COMMENTED** [review]
Since you added `app/assets/stylesheets/shared/tomselect_additional_styles.scss`. We no longer need `app/assets/stylesheets/pages/casa_cases.scss` or `app/assets/stylesheets/pages/case_contacts_form.scss`.

Although those files sound like they might only be loaded on those pages, they actually get loaded on all pages so the styling from `app/assets/stylesheets/shared/tomselect_additional_styles.scss` is enough.

**Comment by elasticspoon** [comment]
@logtay hey, sorry I explained really poorly. I'm not tryna jerk you around or anything. :slightly_frowning_face: 

when i said 

> Since you added app/assets/stylesheets/shared/tomselect_additional_styles.scss. We no longer need app/assets/stylesheets/pages/casa_cases.scss or app/assets/stylesheets/pages/case_contacts_form.scss.

I didn't mean for you to delete the entire files, I meant just the changes you made to them. So basically all this PR needs to contain is the line that imports the new stylesheet + the new stylesheet.

**Comment by logtay** [comment]
@elasticspoon It's okay, I think I misread. I thought I got rid of those first changes, but had some issues on my end, so probably overlooked it. Let me go ahead and do that. Thank you for your patience, I appreciate it.

**Review by elasticspoon — APPROVED** [review]
Nice job! It works.

**Pull request merged**
