### PR TITLE
Refactor court mandate widget js into module and test

### LINKED ISSUE #2444: Jest test for addCourtMandateInput function
**Description**
Write a test for `addCourtMandateInput` in `app/javascript/src/casa_case.js`  
  
see `app/javascript/__tests__/case_contact.test.js` for an example

### LINKED ISSUE #2445: Jest test for courtMandateHtml function
**Description**
Write a test for `courtMandateHtml` in `app/javascript/src/casa_case.js`  
  
see `app/javascript/__tests__/case_contact.test.js` for an example

### PR DESCRIPTION
**Pull request by FireLemons**
### What github issue is this PR for, if any?
Resolves #2445
Resolves #2444

### What changed, and why?
 - Refactored adding a court mandate element into module
 - refactored removing a court mandate element into module
 - simplified js code, js performance improvements
 - reduced repetition in views.en.yml
 - renamed mandates to orders in some places
 - fixed index shifting bug after delete
 - alphabetized `config/locales/views.en.yml`
 - moved court orders list html into a partial
 - `addCourtOrder` sets correct `id` and `name` attributes based on url
 - fixed wrong localization keys references

### How is this tested? (please write tests!) 💖💪
 - updated rspec tests
 - tests for module in jest

img

### CODE REVIEW

**Comment by FireLemons** [comment]
`$$('#court-orders-list-container .court-mandate-entry:nth-child(n+6)')`

**Comment by FireLemons** [comment]
update cypress tests

**Comment by FireLemons** [comment]
type check functions

**Comment by FireLemons** [comment]
decrement shift hidden input name

**Comment by FireLemons** [comment]
Clear all empty court mandates before saving on court orders page

**Comment by FireLemons** [comment]
Find a way to refactor court mandates widget into a partial

**Comment by FireLemons** [comment]
I think we're also using deprecated code 
image

**Comment by FireLemons** [comment]
en views yml not dry

**Comment by compwron** [comment]
Any news on this? :)

**Comment by FireLemons** [comment]
@compwron Yeah I just refactored the court mandate list into a partial. The rails auto generated form elements have different `id` and `name` attributes based on the url. So I'm going to update the court order module to set the correct name and id for new elements when adding blank court orders

**Comment by FireLemons** [comment]
we not based on the url but varying with the url

**Comment by FireLemons** [comment]
what is that 
image

**Comment by FireLemons** [comment]
Hidden textarea?

**Comment by FireLemons** [comment]
bug: every page tries to instantiate court order list

**Comment by FireLemons** [comment]
new tests for different urls

**Comment by FireLemons** [comment]
merge conflicts

**Review by compwron — APPROVED** [review]

**Pull request merged**
