### PR TITLE
 Update view of all casa admin

### PR DESCRIPTION
**Pull request by ErinClaudio**
### What github issue is this PR for, if any?
WIP #1702

### What changed, and why?

- added all case contacts count to view
- failed to add supe-to-vol
- failed to add Case assignments

### How will this affect user permissions?
- Admin permissions: Added new totals to Details sections of all_casa_admins view

### How is this tested? (please write tests!) 💖💪
Not well

### Screenshots please :)
Screen Shot 2021-02-17 at 8 10 52 PM

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### CODE REVIEW

**Comment by compwron** [comment]
We made progress on this during office hours :)

**Comment by ErinClaudio** [comment]
@compwron 

-  I am happy to make the changes to `standardrb lint / ruby_lint (pull_request) ` If you would like. I believe they are related to the hash syntax at the bottom of casa_org.rb. I am not sure if I should leave it alone for consistency.  

-  When attempting to debug the Rspec tests I received a `nomethoderror: undefined method active= `. I am stuck 

-  Cypress not sure about that one

**Comment by compwron** [comment]
> @compwron
> 
>     * I am happy to make the changes to `standardrb lint / ruby_lint (pull_request) ` If you would like. I believe they are related to the hash syntax at the bottom of casa_org.rb. I am not sure if I should leave it alone for consistency.
> 
>     * When attempting to debug the Rspec tests I received a `nomethoderror: undefined method active= `. I am stuck
> 
>     * Cypress not sure about that one

@ErinClaudio 
- yes please fix lint
- I see that cypress is failing with "ActiveRecord::RecordInvalid: Validation failed: Casa org must exist"
- I see that most of the rspec tests are failing, many of them with "Validation failed: Casa org must exist"
This leads me to believe that the new `belongs_to :casa_org` needs an equivalent change in a test factory and possibly also in our db seeds. Happy to work on this during office hours if you want :)

**Comment by compwron** [comment]
merging prior to merging --

**Pull request merged**
