### PR TITLE
Improve mobile UI for volunteers table

### LINKED ISSUE #2624: Make Table Labelling Consistent on Mobile
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently when screen size is sufficiently small, the tables for volunteers and cases are hard to read because they have no labels. The supervisors table however has labels and is easy to interact with at any size. We would like to make the volunteers and cases tables look like the supervisors table with appropriate labels.

**Screenshots of current behavior, if any**  
We want the table on the right to look more like the table on the left:
More Readable Collapsed Tables

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

### PR DESCRIPTION
**Pull request by acrosman**
### What github issue is this PR for, if any?
Resolves #2624

### What changed, and why?
Added mobile labels to volunteers table.

### How will this affect user permissions?
n/a

### How is this tested? (please write tests!) 💖💪
There didn't appear to be automated tests to extend for this, so it was manually tested. But it looks like #2684 suggests a lot of work is needed in this area, so it probably belongs in that process anyway.

### Screenshots please :)

image

### CODE REVIEW

**Comment by acrosman** [comment]
I'm looking at the code climate feedback, and while I don't disagree, given there is an issue to refactor this file in part to avoid warnings of that nature I'm not sure if/how it should be addressed.

**Review by compwron — APPROVED** [review]
Looking good!

Please add tests and either fix or mark ignored the code climate issues
And then we will merge! :)

**Comment by acrosman** [comment]
Happy to make adjustments, but not clear how to make sure to align to the two asks since they are both also related to a larger need in issue #2684 and I don't want to conflict that effort.

Also, I tried and failed to tell code climate to ignore the repetitive code issue – are there directions for the right way to do that?

**Comment by compwron** [comment]
> Happy to make adjustments, but not clear how to make sure to align to the two asks since they are both also related to a larger need in issue #2684 and I don't want to conflict that effort.
> 
> Also, I tried and failed to tell code climate to ignore the repetitive code issue – are there directions for the right way to do that?

Let's keep working on the codeclimate fix- 
https://docs.codeclimate.com/docs/advanced-configuration
https://stackoverflow.com/search?q=%5Bcode-climate%5D+ignore

**Pull request merged**
