### PR TITLE
update bootstrap version

### LINKED ISSUE #3962: yarn oudated bootstrap
**Description**
update bootstrap to the latest version
`yarn outdated` tells us that the newest version of bootstrap is incompatible with our repo
image
update bootstrap to the latest version if possible

**Existing gem(s), file(s) needing updating, changing or deleting**
bootstrap

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by italomatos**
### What github issue is this PR for, if any?
Resolves #3962

### What changed, and why?
update boostrap version from 4.6.2 to 5.2.1 version.

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### CODE REVIEW

**Comment by italomatos** [comment]
> @italomatos thanks for tackling this! How is it going? Do you need any help?

Hi @littleforest , when I updated bootstrap lib, some tests broken, I'm trying to find a problem and fix them. I have not understand why.

```
bin/rspec ./spec/system/notifications/index_spec.rb:93
```

**Comment by italomatos** [comment]
> > @italomatos thanks for tackling this! How is it going? Do you need any help?
> 
> 
> 
> Hi @littleforest , when I updated bootstrap lib, some tests broken, I'm trying to find a problem and fix them. I have not understand why.
> 
> 
> 
> ```
> 
> bin/rspec ./spec/system/notifications/index_spec.rb:93
> 
> ```
done :) ready to review 🚀🚀

**Review by littleforest — COMMENTED** [review]
Glad you got the specs fixed! I am noticing some styling differences on the first page (I didn't investigate further). Would you mind poking through some of the pages on your local machine and on https://casa-qa.herokuapp.com/ to see if you can spot any other styling differences?

For example - 

Local:

Screen Shot 2022-10-02 at 5 36 15 PM


vs QA:

Screen Shot 2022-10-02 at 5 35 18 PM

Local:

Screen Shot 2022-10-02 at 5 37 44 PM


vs QA:

Screen Shot 2022-10-02 at 5 33 41 PM

Thanks!

**Comment by compwron** [comment]
I do think that some of these changes that littleforest posted above are removing formatting that we want

**Comment by compwron** [comment]
Screen Shot 2022-10-04 at 7 39 53 PM
It looks like the modal doesn't close after creating a case contact- this is a problem

**Comment by compwron** [comment]
On the http://127.0.0.1:3000/volunteers page none of the filter views respond to click 
Screen Shot 2022-10-04 at 7 42 28 PM

**Review by compwron — CHANGES_REQUESTED** [review]
There are some broken UI elements. I am so excited to merge this PR once it works!

**Comment by compwron** [comment]
I would love to update this and be able to merge it, do you think you'll come back to this @italomatos ? it's ok if not but if not then we should free it up to be assigned to someone else

**Pull request closed without merging**
