### PR TITLE
Update Travel details section on case contact form

### LINKED ISSUE #5387: Update "4. Enter Travel Details" section on Case Contact Form
## What type(s) of user does this feature affect?
 - volunteers
 - supervisors
 - admins

## Description
This is part of The Case Contact Form Improvement Epic. If you have any questions, please reach out to me, @bcastillo32, and/or @mallorypricedesign. The Case Contact form is one of the most important and heavily used features and your contribution will have a huge impact on CASA volunteers! :) 

## Reference Materials

[Figma File/Prototype](https://www.figma.com/file/QHOE6wHBESpsbxQmlnAZ2L/Case-Contact-Reporting-Process?type=design&node-id=196-19512&mode=design&t=5c48MqogwZ4AZctd-0)

**Steps to view a Figma prototype:**
1. Access the provided link in your web browser.
2. Press the play button located at the top right of the browser window.
3. (Optional) Create a free account and log in. This grants access to view comments left on the file.
4. (Optional) If the prototype extends beyond your screen width, click the "options" dropdown at the top right of the screen and select "fit width."
5. Explore the prototype by clicking different areas to discover interactive elements.

**Styling Chart**

image

## Accessing the Case Contact Form
- Login as a Volunteer
- Click on a case
- Click "+ New Case Contact" button

**Current Version**
image

**Updated version (from Figma File)**
https://www.loom.com/share/9c28d091270649c484ccd49198f0477f

## Acceptance Criteria
- card header should read "1. Travel details (optional)" - see Figma file and styling chart referenced above
- each section of card should be updated to match Figma File - see Figma File and styling chart referenced above
- Card text should use correct styling - see Figma file and styling chart referenced above
- break up card into the 2 sections. 
- Second Section Header should read "2. Other expenses (optional)" and styling and text should match the Figma file/prototype and styling chart.

image

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by JoshDevHub**
### What github issue is this PR for, if any?
Resolves #5387 

### What changed, and why?
Updated  style of Travel Expenses section of the case contact form to match new design.

[Link to Figma Design](https://www.figma.com/file/QHOE6wHBESpsbxQmlnAZ2L/Case-Contact-Reporting-Process?type=design&node-id=196-19512&mode=design&t=5c48MqogwZ4AZctd-0)

### How will this affect user permissions?
- Volunteer permissions: N/A
- Supervisor permissions: N/A
- Admin permissions: N/A

### How is this tested? (please write tests!) 💖💪
N/A

#### How it looks with this PR:
screenshot of updated form

#### How it used to look:
screenshot of how form used to look

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by JoshDevHub** [comment]
Will definitely pursue those system spec failures :sweat_smile:

**Comment by compwron** [comment]
Screenshot 2024-03-26 at 8 15 37 PM
What's up with the weird branch name?

**Comment by compwron** [comment]
spec are failing, please fix

**Comment by JoshDevHub** [comment]
> What's up with the weird branch name?

It was automatically generated from the title of the issue. Glad to change it to get rid of the character escaping.

> spec are failing, please fix

Will get to it this week :thumbsup:

**Comment by bcastillo32** [comment]
@compwron can this be approved? :)

**Comment by compwron** [comment]
looking...

**Comment by compwron** [comment]
In the future, please add screenshots to PRs that change UI

**Review by compwron — APPROVED** [review]

**Pull request merged**
