### PR TITLE
Update styles for new case contact form

### LINKED ISSUE #5498: Minor UI updates to Case Contact Form
**Description**
Some minor UI changes to increase accessibility

1. Update all checkbox and radio button outlines in the unchecked state to be #757575 instead of #E5E5E5 
2. Right-align form buttons and make them title case
    1. On pages that include the “Save and Continue” button, this button should be the rightmost, and the “Back” button should be 10 pixels to the left
    2. On pages that include the "Submit" button, this button should be the rightmost, and the "Back" button should be 10 pixels to the left
    3. For the "New court report topic" in the admin portal, "Submit" and "Back" should be right aligned with "Submit" being the rightmost.
3. For Mobile view only:
    1. Reduce the size of the H1 “Record new case contact” to size H2
    2. Reduce the size of the H2 “Contact Details” to size H3

For reference, please see the [Figma](https://www.figma.com/file/QHOE6wHBESpsbxQmlnAZ2L/Case-Contact-Reporting-Process?type=design&node-id=148%3A16461&mode=design&t=iv2Vrg72rct7UwRQ-1) document.

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by jp524**
### What github issue is this PR for, if any?
Resolves #5498.

### What changed, and why?

- [x] Update all checkbox and radio button outlines in the unchecked state to be #757575 instead of #E5E5E5
- [x] Right-align form buttons and make them title case
  - [x] On pages that include the “Save and Continue” button, this button should be the rightmost, and the “Back” button should be 10 pixels to the left
  - [x]  On pages that include the "Submit" button, this button should be the rightmost, and the "Back" button should be 10 pixels to the left
  - [ ] For the "New court report topic" in the admin portal, "Submit" and "Back" should be right aligned with "Submit" being the rightmost.
- [x] For Mobile view only:
  - [x] Reduce the size of the H1 “Record new case contact” to size H2
  - [x] Reduce the size of the H2 “Contact Details” to size H3

As commented in the issue, for item 2.iii we weren't able to find the "New court report topic" in the admin portal. We were using the latest code from the `main` branch. If this is a feature that is currently being worked on, we can circle back to it later when it is implemented.

### How will this affect user permissions?
- Volunteer permissions: n/a
- Supervisor permissions: n/a
- Admin permissions: n/a

### How is this tested? (please write tests!) 💖💪
Since this is a style update, we checked in our local development environment that the changes were correctly implemented. Refer to screenshots below

### Screenshots please :)
**Desktop view showing the new outline colour for checkboxes and radio buttons, as well as the aligned buttons**
Screenshot 2024-02-07 at 09 30 04

**Mobile view showing the reduced heading size**
Screenshot 2024-02-07 at 09 34 32

**Mobile view showing the button layout is per the Figma file provided (different from the desktop view)**
Screenshot 2024-02-07 at 09 35 10

### CODE REVIEW

**Comment by jp524** [comment]
Since we changed the case used for buttons some tests are not passing anymore. @Natblow and I will address this

**Comment by jp524** [comment]
The `standardrb lint / ruby_lint` CI is failing because of this file: 20231125151610_set_case_contacts_as_active.rake

We haven't modified this file though so I think it might have been changed on main.
I can submit a PR for it if that's okay with you @compwron.

**Comment by littleforest** [comment]
> I can submit a PR for it if that's okay

That would be great, thanks!

**Comment by jp524** [comment]
Latest commits on `main` have fixed the lint issue. All checks are now passing so this PR is ready for review. Thanks!

**Pull request closed without merging**
