### PR TITLE
Dss now renders as DSS 

### LINKED ISSUE #655: Case contact show "Dss" as "DSS"

### PR DESCRIPTION
**Pull request by strangrjrjr**
### What github issue is this PR for, if any?
Resolves #655 

### What changed, and why?
The form renders constants defined in the `case_contact` model. `titleize` looks at `config/initializers/inflections.rb`, where we can define things like acronyms and special pluralization rules. Setting DSS as an acronym will allow it to render properly while not effecting the capitalization of the other constants.

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### How is this tested? (please write tests!) 💖💪
Tests view to verify the existence of 'DSS'.

### Screenshots please :)
**Before**
Screen Shot 2020-09-05 at 10 09 52 AM

**After**
Screen Shot 2020-09-05 at 10 12 56 AM

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### CODE REVIEW

**Comment by compwron** [comment]
Very fancy!!!
Can we get a test with that please :)

**Comment by strangrjrjr** [comment]
Our change passes existing tests; would it make sense to add an additional check on the view to ensure proper rendering of 'DSS'?

**Comment by compwron** [comment]
> Our change passes existing tests; would it make sense to add an additional check on the view to ensure proper rendering of 'DSS'?

I think it's worth testing that our functionality works because if we break it (by renaming something maybe) it won't be obvious why.

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
Very nice :) 💖

**Pull request merged**
