### PR TITLE
fix: deprecated docker-compose

### PR DESCRIPTION
**Pull request by elasticspoon**
### What github issue is this PR for, if any?
Resolves #XXXX

### How is this **tested**? (please write tests!) 💖💪
_Note: if you see a flake in your test build in github actions, please post in slack #casa "Flaky test: <link to failed build>" :) 💪_
_Note: We love [capybara](https://rubydoc.info/github/teamcapybara/capybara) tests! If you are writing both haml/js and ruby, please try to test your work with tests at every level including system tests like https://github.com/rubyforgood/casa/tree/main/spec/system_ 

### Screenshots please :)
_Run your local server and take a screenshot of your work! Try to include the URL of the page as well as the contents of the page._ 

### Feelings gif (optional)
_What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:_
`alt text`

### CODE REVIEW

**Comment by thejonroberts** [comment]
I started looking at this too, #5964 is a find and replace for all `docker-compose` to `docker compose`. I opened it to merge into this branch, for the moment. [This is the only thing that concerns me](https://docs.docker.com/compose/migrate/#migrating-running-projects) (who has no idea what deployment looks like yet)

**Comment by elasticspoon** [comment]
Yea. If I'm being honest I don't understand why it's happening. I would expect the older command to either work or not work consistently but the fact that it is flaky is just weird to me.

**Comment by elasticspoon** [comment]
> I started looking at this too, #5964 is a find and replace for all `docker-compose` to `docker compose`. I opened it to merge into this branch, for the moment. [This is the only thing that concerns me](https://docs.docker.com/compose/migrate/#migrating-running-projects) (who has no idea what deployment looks like yet)

Actually, all our stuff is deployed via heroku, which idk what they do exactly but it's not using compose. So I'm perfectly fine with a find and replace. I do wish I knew that an error as a result of swapping from v1 to v2 with running stuff might look like to add that to a wiki.

**Comment by thejonroberts** [comment]
I'm guessing the flakiness is probably a cacheing thing -- every once in a while we 'get lucky' and hit a GitHub server that still supports it, but it's becoming less common. But not important. If deploy doesn't use compose / these changes don't affect that, then I'd say we don't need to worry about v1 compatibility.

**Comment by elasticspoon** [comment]
closed in favor of https://github.com/rubyforgood/casa/pull/5964

**Pull request closed without merging**
