### PR TITLE
Remove never text from most recent contact type dates

### PR DESCRIPTION
**Pull request by FireLemons**
### What changed, and why?
Removed "never" text from appearing

### Screenshots please :)
Before  
image
After  
image

### CODE REVIEW

**Comment by compwron** [comment]
Why do you want to remove the never text?

**Comment by FireLemons** [comment]
@compwron I think it clutters the page and is confusing if a volunteer has never put in a case contact

**Comment by compwron** [comment]
Let's talk to the stakeholders before doing this, I'm not sure it fits what they asked for

**Comment by compwron** [comment]
Let's not for now

**Pull request closed without merging**
