### PR TITLE
796 - Add 1 hour session inactivity timeout, and forced expiration on browser quit 

### LINKED ISSUE #796: User session ends when the window is closed OR after 1 hour of inactivity
**What type of user is this for? [admin/supervisor/volunteer/all or All CASA Admin]**
all including All CASA Admin

**Description**
When a user closes the browser window containing an active user session OR after one hour of activity has passed in a user session (whichever happens first), the session should automatically end, and the user should be logged out.

### PR DESCRIPTION
**Pull request by ryanmrodriguez**
### What github issue is this PR for, if any?
Resolves #796 

### What changed, and why?
- Removed 'Remember Me' functionality
- Added session timeout

### How will this affect user permissions?
- Volunteer permissions: No change
- Supervisor permissions: No change
- Admin permissions: No change

### How is this tested? (please write tests!) 💖💪
To manually test you can login and quit your browser to confirm session has ended, and that you are prompted to login again.
Also added a spec to test basic session timeout.

### Screenshots please :)
image

### Feelings gif (optional)
What gif best describes your feeling working on this issue?
alt text

### CODE REVIEW

**Comment by KatherineMuedas** [comment]
LGTM!

**Comment by ryanmrodriguez** [comment]
A couple of notes @Zrrrpy. On Mac you ned to actually 'Quit' the browser (only pertaining to the forced expiration on browser close), since Mac doesn't actually kill the process when clicking the red X in the window. Also there is a column "remember_created_at" that could be removed from users and admins table if wanted. It's harmless to keep, but we didn't want to remove as it felt a bit intrusive messing with your schema. It also allows you to easily re-enable the Remember Me functionality if you ever need it again. If you do wish to remove it, a simple migration can be added later.

```rb
class RemoveRememberableFromUsersAndAdmins < ActiveRecord::Migration[6.0]
  def change
    remove_column :all_casa_admins, :remember_created_at, :datetime
    remove_column :users, :remember_created_at, :datetime
  end
end
```

**Review by drborges — APPROVED** [review]
LGTM

**Comment by Zrrrpy** [comment]
Thanks @ryanmrodriguez! good with all you laid out above.

**Comment by Zrrrpy** [comment]
Tested in QA on the frontend in Safari and Chrome and works in both! Will deploy to staging in a bit.

**Pull request merged**
