### PR TITLE
Modify volunteers#index system test to not use sleep

### LINKED ISSUE #5548: refactor test to not need sleep
refactor test to not need sleep

_Originally posted by @compwron in https://github.com/rubyforgood/casa/pull/5144#discussion_r1501876180_

### PR DESCRIPTION
**Pull request by jp524**
### What github issue is this PR for, if any?
Resolves #5548

### What changed, and why?
A system test in Volunteers#index was changed to not use `sleep(1)` after a checkbox is clicked. Instead, an assertion is used to make sure the checkbox was clicked and has the intended effect before moving on to the next assertions.

### How will this affect user permissions?
- Volunteer permissions: n/a
- Supervisor permissions: n/a
- Admin permissions: n/a

### How is this tested? (please write tests!) 💖💪
Ran the test suite locally.

### Screenshots please :)
These are the console logs from RSpec, showing that the test execution time has been reduced:
```
# BEFORE (with sleep)
casa % be rspec spec/system/volunteers/index_spec.rb:259                                                                                                                                                                               
Neither Pony nor ActionMailer appear to be loaded so email-spec is requiring ActionMailer.                                                                                                                                                             
Run options: include {:focus=>true, :locations=>{"./spec/system/volunteers/index_spec.rb"=>[259]}}                                                                                                                                                     
                                                                                                                                                                                                                                                       
Randomized with seed 33125                                                                                                                                                                                                                             
.                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                       
Finished in 3.06 seconds (files took 2.6 seconds to load)                                                                                                                                                                                              
1 example, 0 failures                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                       
Randomized with seed 33125                                                                                                                                                                                                                             

# AFTER (with assertion)                                                                                                                                                                                                          
casa % be rspec spec/system/volunteers/index_spec.rb:259                                                                                                                                                                               
Neither Pony nor ActionMailer appear to be loaded so email-spec is requiring ActionMailer.                                                                                                                                                             
Run options: include {:focus=>true, :locations=>{"./spec/system/volunteers/index_spec.rb"=>[259]}}                                                                                                                                                     
                                                                                                                                                                                                                                                       
Randomized with seed 56948                                                                                                                                                                                                                             
.                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                       
Finished in 2.37 seconds (files took 3.14 seconds to load)                                                                                                                                                                                             
1 example, 0 failures                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                       
Randomized with seed 56948    
```

### CODE REVIEW

**Comment by jp524** [comment]
From the test suite run in Docker it looks like there are more flaky tests related to the Volunteer#index system tests. I'll have a look at those as well.

**Comment by schoork** [comment]
> From the test suite run in Docker it looks like there are more flaky tests related to the Volunteer#index system tests. I'll have a look at those as well.

Honestly @jp524, take them out. I wrote them and they are just too flaky with the way the table is loaded. Can you change them to xit and comment out the middle? Once we get Hotwire on this page I think the tests should work well.

**Comment by jp524** [comment]
@schoork I skipped the two tests that were flaky in the initial CI run on Docker, but now more tests are failing within that same file. I would like to defer to you to chose which test to skip or not.

I'm also okay with closing this PR if the change I added to the test isn't relevant anymore.

**Comment by schoork** [comment]
@jp524 No problem. I'll take a look today or tomorrow. Keep this open and I'll just push into it.

**Review by schoork — APPROVED** [review]

**Pull request merged**
