### PR TITLE
Update court_report_due_date when a new court_date is added

### LINKED ISSUE #2905: Set case due date automatically to 3 weeks before hearing date when new future court date is added
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently when we add a Next Court Date is set the Court Report Due Date has to be set separately. We would like to make it so that setting the Next Court Date automatically sets the Court Report Due Date to the date three weeks before the Next Court Date. We would like the Court Report Due Date to remain able to be changed manually later. We would just like it to set automatically at the time of adding a Next Court Date. 

**Screenshots of current behavior, if any**  
Next Court Date with No Court Report Due Date

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by geeksilva97**
### What github issue is this PR for, if any?
Resolves #2905

### CODE REVIEW

**Review by compwron — COMMENTED** [review]
Please add a test :)

**Comment by geeksilva97** [comment]
> Please add a test :)

I'm working on it :)

**Comment by geeksilva97** [comment]
Hi, @compwron. Could you review it?

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
:)

**Pull request merged**
