### PR TITLE
Issue-4328/Adds new theme to volunteers pages

### LINKED ISSUE #4328: New Theme - volunteers pages
**Description**

This is part of #4304

We're updating the theme of the app to use the [plainadmin](https://plainadmin.com/docs/) theme and going through the process of converting the site to that theme. 

## Directions

* Checkout the `new_theme` branch and create a branch off of that branch for your work.
* Update all the views in the the `/views/volunteers` to use the new theme.
* The `/views/supervisor/index.html.erb` has already been converted to use the new theme, use it as a reference when converting over.
* If there are missing elements use the [plainadmin docs](https://plainadmin.com/docs/) and the [bootstrap 5 docs](https://getbootstrap.com/docs/5.1/getting-started/introduction/) as reference.
* When submitting your PR submit it against the `new_theme` branch.

The following files need to be converted to the new theme:
- [ ] _form.html.erb
- [ ] _manage_active.html.erb
- [ ] _manage_cases.html.erb
- [ ] _manage_supervisor.html.erb
- [ ] _notes.html.erb
- [ ] _send_reminder_button.html.erb
- [ ] _volunteer_reminder_form.html.erb
- [ ] edit.html.erb
- [ ] index.html.erb
- [ ] new.html.erb

### Things to consider:

It is difficult to keep the `new_theme` branch up to date so please be considerate in claiming issues and keep the team apprised of your progress.

### PR DESCRIPTION
**Pull request by anshu1992**
### What github issue is this PR for, if any?
Resolves #4328

### What changed, and why?
Html tags and classes changed for updating to the new theme. Reordered an import statement in `app/javascript/application.js` to eliminate a javascript error.
  
  ##### Before reordering:
  
  JS ERROR

  ##### After reordering:
  
  Error free

### How will this affect user permissions?
- Volunteer permissions: Not gonna affect.
- Supervisor permissions: Not gonna affect.
- Admin permissions: Not gonna affect.

### How is this tested? (please write tests!) 💖💪
This is tested visually. Everything looks good according to the new theme.

### Screenshots, please :)
1. Index Page

CASA Volunteer Tracking

2. Edit Page (includes changes for partials used)

CASA Volunteer Tracking

3. New Volunteer Page

CASA Volunteer Tracking

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:

Had Fun

### Feedback, please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by seanmarcia** [comment]
Hey @anshu1992 this is amazing!!! Thank you so much for figuring out the javascript import issue and getting the issue working.

There are a couple fixes it would be amazing if you could add.
* Add the `btn-sm` class to all the buttons so the buttons are consistent size to the other buttons in the app.
* In the manage cases and notes sections can you use the same styling as `views/hearing_types` uses for actions
* Finally can you add icons to your buttons :) You should be able to find examples of the various icons elsewhere, if you are stuck let me know!

Thank you so so so so much for this. It is fantastic!

**Comment by anshu1992** [comment]
Thank you @seanmarcia! Changes coming up.

**Comment by anshu1992** [comment]
I have made the changes you asked for. Please let me know if more changes are needed. Following are some screenshots:

CASA Volunteer Tracking (1)

CASA Volunteer Tracking

CASA Volunteer Tracking

**Comment by seanmarcia** [comment]
Awesome, thanks for making the changes!

**Comment by seanmarcia** [comment]
I love the icon you used for impersonate btw :)

**Comment by anshu1992** [comment]
> I love the icon you used for impersonate btw :)

Thank you! I have a small suggestion regarding icons. Line icons are minimal, and sometimes I need help finding the relevant icons. I had to use the closest-looking ones. 

I have used font-awesome in many projects and found it an awesome library for icons. For example, we could have used their [user-secret](https://fontawesome.com/icons/user-secret?s=solid&f=classic) for impersonation. All of these are available with the free version.

**Comment by seanmarcia** [comment]
So, you're offering to switch the icons over? :) I think it would be a great idea since font awesome is more widely used and better known by developers.

**Comment by anshu1992** [comment]
Yes, switching will provide developers a wide variety of icons.

**Pull request merged**
