### PR TITLE
Use datepicker for selecting dates

### LINKED ISSUE #820: Occurred at calendar not displaying in Safari on desktop and mobile web
Part of epic #3

**What type of user is this for? [admin/volunteer/supervisor/all or All CASA Admin]**
primarily volunteer, but also admin and supervisor

**Where does/should this occur?**
On the create/edit case contact page accessible via all user dashboards.

**Desired behavior**
A small calendar icon should display on the far right of the "Occurred at" field. Clicking this calendar should trigger a calendar pop out that users can use to select a date to associate with their `case_contact`. 

**Current behavior**
No calendar icon displays in the "Occurred at" field **when accessed on Safari** (mobile and desktop web). 

The fix to this will probably to use some library which makes Safari respect https://caniuse.com/input-datetime
Screen Shot 2020-10-11 at 10 30 11 AM
I checked and it it does work on Firefox and Chrome.

### PR DESCRIPTION
**Pull request by NickSchimek**
### What github issue is this PR for, if any?
Resolves #820 

### What changed, and why?

The date/calendar picker was not displaying on all browsers because the HTML5 date type is not well supported. `bootstrap-datepicker` was already installed and being used in the reports view for selecting dates. Added the necessary attributes to the `occurred_at` field to enable it in the contact form. However, the calendar was not styled correctly and was difficult to read since the spacing between columns was virtually non-existent (This was also an issue on the reports view). Imported the `bootstra-datepicker` css file which fixed the styling issue.

The keyboard can also be used to select a date. The datepicker also displays on my mobile device, which looks better than the native date picker: Here is screen cap of native date picker on iphone x. For whatever reason it was not displaying correctly.

image0

I would prefer to have the native date picker on mobile, but I'm not that well versed in the frontend and I'm not willing to investigate why this is happening. Also it does not look like we are supporting mobile views at this point in time? The datepicker works well on the mobile device and can be entered in manually via the keyboard. Although, I did find a bootstrap css file that was not being used, and when imported it made everything have a smaller/nicer font on the page. This might fix the issue with the native date picker for the mobile phone. I decided to keep that css file out, because the page had been optimized for the larger font display.

### How will this affect user permissions? N/a
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### How is this tested? (please write tests!) 💖💪

Visually

### Screenshots please :)

Screen Shot 2020-10-16 at 6 04 14 PM

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### CODE REVIEW

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
mobile- we want to be more mobile friendly, but currently that has not been focused on
very nice! :)

**Comment by NickSchimek** [comment]
> we want to be more mobile friendly

OK. If that is the case then I think we should use `type=date` setting for mobile devices. I viewed the page on my mobile device using `type=date` and had no issues with Safari, chrome, duck-duck-go mobile browser (FireFox probably works). The native date picker worked like a charm. Where I saw the issue yesterday was with the Brave browser, The brave browser is built off of the chrome browser so I'm surprised it had issues. There was no effect on the native date picker when using the aforementioned bootstrap css file; however the mobile page was easier to view as the font was displayed in a way that could be easily read without having to scroll so much.

I found an article that said `type=date` is fully supported on mobile web browsers, apparently that is not always the case.

**Comment by compwron** [comment]
Sounds good.

**Comment by compwron** [comment]
You are invited to the CASA asynchronous retrospective-and-futurespective! Please take a look at https://bit.ly/casaretro (no login required) and add at least one note! Even if it's just "I was here and you are cool" or "omg y'all why do you keep messaging me" we want to hear it. <3
Next week Wednesday 18 November @ 6pm Pacific time we will Zoom about the board and talk about themes and takeaways. (Zoom link in our calendar at http://bit.ly/casacal or slack #casa channel https://rubyforgood.herokuapp.com/ )
Please ESPECIALLY add lots of notes if you won't be able to make it on Wednesday to talk!
* Note: the board will be monitored for spam; message me or any team lead if you see a problem
https://bit.ly/casaretro

**Pull request merged**
