### PR TITLE
Adds 'Select One' as default

### LINKED ISSUE #1430: Customize emancipation checklist "empty" options
**What type of user is this for? volunteer/supervisor/admin/all**
volunteer / all

**Description**
Question: Youth is employed. 
replace "empty" with "Not employed"
AND make the first (auto-selected field) "select one" (null in db?) and choosing "Not employed" records that a choice has been made

Question: Youth is attending an educational or vocational program. 
replace "empty" with "Not attending" (we will consult with stakeholders about options around incomplete attendance)
AND make the first (auto-selected field) "select one" (null in db?) and choosing "Not attending" records that a choice has been made

Question: Youth has a high school diploma or equivalency.
replace "empty" with "No"
AND make the first (auto-selected field) "select one" (null in db?) and choosing "No" records that a choice has been made

**Screenshots of current behavior, if any**
Screen Shot 2020-12-09 at 6 26 01 PM

### PR DESCRIPTION
**Pull request by ghost**
### What github issue is this PR for, if any?
Resolves #1430 

### What changed, and why?
- The default selection was changed to "Select One" from "empty".  "Select One" is defaulted and disabled to require a volunteer to select a valid choice.
-  New select options were added as valid choices to the seeds file.

### How will this affect user permissions?
- Volunteer permissions: N/A
- Supervisor permissions: N/A
- Admin permissions: N/A

### How is this tested? (please write tests!) 💖💪
Added additional system test to `spec/system/casa_cases/emancipation/show_spec.rb`.

### Screenshots please :)

image

Co-authored-by: [Noah Clark](https://github.com/noahc)

### CODE REVIEW

**Comment by ctreptow** [comment]
We weren't sure if modifying the seeds file is enough?  They will also need to be created in production.

**Comment by compwron** [comment]
@ctreptow to create files in production, use our `after_party` functionality :)

**Comment by ctreptow** [comment]
@compwron Done!

**Comment by littleforest** [comment]
@ctreptow thanks for working on this! Can you also make the other changes requested in the ticket?

**Review by littleforest — APPROVED** [review]
Thanks for working on this! (Missed that the Select One is part of a loop for my original comment, but all is good!) 💯

**Pull request merged**
