### PR TITLE
Typography Update for Headers

### PR DESCRIPTION
**Pull request by coleerikson**
- - Please see comment below - - -

### What changed, and why?
- Updated page headers/section title to use bolder yet smaller font.
- Also updated a couple buttons to from `btn-info` to other variations that suit the page context better.

### How will this affect user permissions?
No affects. Just updating page/section titles.

### How is this tested? (please write tests!) 💖💪
No extra tests needed, but other tests updated.

### Screenshots please :)
Screen Shot 2020-09-25 at 3 53 59 PM

### CODE REVIEW

**Comment by coleerikson** [comment]
Failing specs based on Travis CI not sizing the browser to a larger screen resolution. Happy to help this along, but not sure why CI isn't accepting screen size option we passed in another PR.

**Comment by compwron** [comment]
This is a lot of merge conflicts! 😅 I'm not sure what is best to do here. Hopefully Power can sort it out on Monday if they have time 💖

**Comment by coleerikson** [comment]
I swear it was clean when I PR'd! lol I'll take a look today +1

**Comment by drborges** [comment]
@coleerikson this is probably due to changes from the `new-layout` branch. It may be simpler to just apply the typography patterns all over again.

**Comment by coleerikson** [comment]
Totally. All good.

**Comment by mdworken** [comment]
@coleerikson I'm going to close this PR for now since it's gonna end up being easier to redo this on a fresher branch. But feel free to re-open if I misinterpreted!

**Comment by compwron** [comment]
You are invited to the CASA asynchronous retrospective-and-futurespective! Please take a look at https://bit.ly/casaretro (no login required) and add at least one note! Even if it's just "I was here and you are cool" or "omg y'all why do you keep messaging me" we want to hear it. <3
Next week Wednesday 18 November @ 6pm Pacific time we will Zoom about the board and talk about themes and takeaways. (Zoom link in our calendar at http://bit.ly/casacal or slack #casa channel https://rubyforgood.herokuapp.com/ )
Please ESPECIALLY add lots of notes if you won't be able to make it on Wednesday to talk!
* Note: the board will be monitored for spam; message me or any team lead if you see a problem
https://bit.ly/casaretro

**Pull request closed without merging**
