### PR TITLE
New Layout!

### PR DESCRIPTION
**Pull request by jasperfurniss**
### What changed, and why?
This PR implements a new sidebar layout for the entire application. This is a rough first version that will need additional code to make it more refined and fully working. 

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Screenshots please :)
Mockup:
supervisor-dashboard-page-001

Initial MVP (still a work in progress)
Screen Shot 2020-09-22 at 12 27 12 PM

### Feelings gif (optional)
What gif best describes your feeling working on this issue?

alt text

### CODE REVIEW

**Comment by compwron** [comment]
It seems very promising! I notice in the screenshot that the CASA logo is at top left instead of at the bottom next to the r4g logo, which feels weird to me. 
Let's also make sure that the links to Admin/Supervisor capabilities like reports and imports don't get lost in this transition- the screenshot looks like it's for a volunteer with two cases. I would like to see the supervisor and admin, and all-casa-admin views also. 
This is very very cool progress! I am excite :)

**Comment by jasperfurniss** [comment]
> It seems very promising! I notice in the screenshot that the CASA logo is at top left instead of at the bottom next to the r4g logo, which feels weird to me.
> Let's also make sure that the links to Admin/Supervisor capabilities like reports and imports don't get lost in this transition- the screenshot looks like it's for a volunteer with two cases. I would like to see the supervisor and admin, and all-casa-admin views also.
> This is very very cool progress! I am excite :)

I updated the original Comment section above with the mockup. Logo will go in the top left. Still a work in progress. Footer (although not currently in the mockup) will be much smaller and fixed to the bottom of the page. I think there is a separate ticket already in progress for that actually.

**Comment by drborges** [comment]
A great start indeed! 🎉

@jasperfurniss are you planning on adding media queries for the mobile version of the sidebar in this PR?

**Comment by jasperfurniss** [comment]
> A great start indeed! 🎉
> 
> @jasperfurniss are you planning on adding media queries for the mobile version of the sidebar in this PR?

@drborges Yes! Cole and I basically held off for the time being. But that's something we want to add either before Thursday or end of week. Basically we will come back through and do that in a separate ticket. That was the thought at least.

**Comment by compwron** [comment]
Wow wow wow!

**Review by compwron — APPROVED** [review]

**Comment by drborges** [comment]
This is looking pretty good in my local smoke tests. If no one has any concerns, I'm thinking we can go ahead and merge this into master so QA testing can start and we may be able to address anything that needs adjusting sooner rather than later.

I'll be adding a few more specs in a follow-up PR soon.

**Review by drborges — APPROVED** [review]

**Pull request merged**
