### PR TITLE
Allow admins to edit assigned volunteers on edit casa_case page

### LINKED ISSUE #90: Admin view/edit case page should include volunteer/s assigned to the case
Part of epic #4 (Admin Dashboard)

**What type of user is this for? [volunteer/supervisor/admin/all]**
This feature is for **admins** and should not change what non-admins can see or do. 

**Where does/should this occur?**
Currently, [in the admin view/edit case view](https://casa-r4g-staging.herokuapp.com/casa_cases/12/edit), admins only see case info.

**Description**
Add to this view the volunteer/s currently **actively** assigned to the case. ( `case_assignment.is_active == true` )
Display volunteer as  volunteer **name** not id or email. If volunteer name is not in the db schema yet, display volunteer email. The volunteer's name (or email) should be a link to the admin view/edit volunteer page.

**Screenshots**
https://casa-r4g-staging.herokuapp.com/casa_cases/14/edit
Screen Shot 2020-04-18 at 3 36 32 PM

### PR DESCRIPTION
**Pull request by colinsoleim**
### What github issue is this PR for, if any?

Resolves #90 

### Checklist

* [x] I have performed a self-review of my own code
* [x] I added comments, particularly in hard-to-understand areas
* [ ] I updated the `/docs`
* [x] I added tests that prove my fix is effective or that my feature works
* [x] `bundle exec rake` passes locally
* [ ] My PR title includes "WIP" or is [draft PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests) if work is in progress

### What changed, and why?

This PR gives admins the ability to assign and unassign volunteers on the existing edit_casa_case view.

### How will this affect user permissions?

Only admins can access the new page

### How is this tested?

New tests have been added and local testing

### Screenshots please :)

Screen Shot 2020-05-22 at 11 40 22 AM

### CODE REVIEW

**Comment by compwron** [comment]
it looks like the build is failing with:
```
Failure/Error: expect(page.all("table#volunteers tr").count).to eq 4
     
       expected: 4
            got: 6
```

That's probably just the new UI element showing up in an unspecific page search

**Comment by colinsoleim** [comment]
> it looks like the build is failing with:
> 
> ```
> Failure/Error: expect(page.all("table#volunteers tr").count).to eq 4
>      
>        expected: 4
>             got: 6
> ```
> 
> That's probably just the new UI element showing up in an unspecific page search

Yeah I just edited the test, and it's still failing even after the initial expect was removed. It looks like the jquery datatable filtering isn't working on Travis for some reason. I'll look into it now.

**Comment by colinsoleim** [comment]
Looks like there was an error with this test after we tried debugging some of the issues with the Heroku CSS. For some reason, upgrading some of the npm packages caused the issue, might have to be careful with that in the future in case we do have to upgrade. I reverted the versions for now, and everything appears to be fixed.

**Comment by compwron** [comment]
Thanks!! 
Argh

**Pull request merged**
