### PR TITLE
Next 15 tests new theme

### PR DESCRIPTION
**Pull request by ShamiTomita**
### What github issue is this PR for, if any?
Resolves parts of #4455 

### What changed, and why?

Changes to the following Spec Files:

[X] ./spec/system/case_contacts/new_spec.rb 

[X] ./spec/system/reports/export_data_spec.rb 

[X] ./spec/views/checklist_items/new.html.erb_spec.rb 

[X] ./spec/requests/case_court_reports_spec.rb 

[X] ./spec/system/supervisors/edit_spec.rb 

[X] ./spec/system/all_casa_admins/casa_orgs/new_spec.rb:63

[X] ./spec/views/hearing_types/edit.html.erb_spec.rb 

Had to change ./app/javascript/src/case_contact.js in order for the modal to show up.

Additionally, the changes currently submitted for ./spec/system/reports/export_data_spec.rb  don't include the "proper" cosmetic changes yet so would love some guidance on that. Kind of looks a little weird but the tests pass at the very least.

 
Screenshot 2023-02-08 at 6 13 27 PM

Also, I couldn't figure out ./spec/views/layouts/application.html.erb_spec.rb because the error was that the stack level is too deep? Any thoughts?

Screenshot 2023-02-08 at 6 51 39 PM

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by seanmarcia** [comment]
There were issues on other pages with the modals not appearing -- this was due to how bootstrap4 vs bootstrap5 implements modals and the switch from `data-toggle` to `data-bs-toggle`

**Comment by seanmarcia** [comment]
Fixed the stack level too deep. You might want to pull the changes from master in -- I think it fixes all the issues you point out.

**Comment by ShamiTomita** [comment]
Oh amazing, thank you Sean. I’ll do that and go over the tests one more
time when I’m back home. Did you have a chance to look at the export data
select form?

**Comment by seanmarcia** [comment]
I looked at the form -- it looks correct to me. It may be fixed on your branch when you pull in the changes.

**Comment by ShamiTomita** [comment]
Awesome, thank you!

**Comment by ShamiTomita** [comment]
Hi @seanmarcia, sorry for any inconveniences that arose from this PR. I went over the files and reverted the changes I had made to the thank_you modal and the case_contact javascript file. I'm including the changes I made to the reports/index.html.erb for the export_data spec but I did change prompt:true to prompt:false. Removing the prompt from the selections seems to keep the reports from being blank if they're selected. Please let me know if there's anything else I should change.

**Pull request closed without merging**
