### PR TITLE
Hide Deactivated Supervisors from /supervisors page by default #2714

### LINKED ISSUE #2714: Hide Deactivated Supervisors from /supervisors page by default
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Hide Deactivated Supervisors from /supervisors page by default
When a supervisor is deactivated, do not show them. 
Also add a toggle/button to show deactivated supervisors if the user wants to

**Screenshot
Screen Shot 2021-10-08 at 6 45 06 PM

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by matisnape**
### What github issue is this PR for, if any?
Resolves #2714

### What changed, and why?
As specified in the issue, there was a need to filter out deactivated supervisors by default and add a filter to be able to show them.

### How will this affect user permissions?
Permissions not affected

### How is this tested? (please write tests!) 💖💪
Here I would need a hand - where should I test it? Controller or view or both? Haven't seen supervisor controller tests

### Screenshots please :)
I added a button to Show/Hide deactivated supervisors
CASA Volunteer Tracking 2021-10-10 21-34-54
CASA Volunteer Tracking 2021-10-10 21-49-33

### Feelings gif (optional)
What gif best describes your feeling working on this issue? 
alt text

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

PS. 
Will work on the tests. Although I don't get it why they fail and when I test it manually, all is good

### CODE REVIEW

**Review by compwron — APPROVED** [review]
Looks good. Please fix the tests :)

**Review by compwron — APPROVED** [review]
Let's add a test for this
And fix the failing tests
Looks like a good change :)

**Comment by matisnape** [comment]
> Let's add a test for this
> 
> And fix the failing tests
> 
> Looks like a good change :)

Yeah, I'm working on this and started a discussion on Slack, because my ideas don't seem to work :)

**Comment by matisnape** [comment]
Hi @compwron 
I added and fixed the tests. 
There's one failing spec that I didn't touch that relates to Devise config. Is there something missing in my branch?

**Comment by compwron** [comment]
Let's merge and fix the test in a follow-up PR

**Pull request merged**
