### PR TITLE
Rename "Court Mandates" to "Court Orders"

### LINKED ISSUE #2599: Rename all court mandates to court orders in the code
Court Mandates have been named court orders on the frontend. Update all remaining code to refer to court mandates as court orders.

 - Create a migration to rename the table
 - Rename the model (`app/models/case_court_mandate.rb`)
 - rename the controller (`app/controllers/case_court_mandates_controller.rb`)
 - rename the policy (`app/policies/case_court_mandate_policy.rb`)
 - update any tests
see https://stackoverflow.com/questions/11924124/how-to-rename-rails-controller-and-model-in-a-project

### PR DESCRIPTION
**Pull request by efgalvao**
### What github issue is this PR for, if any?
Resolves #2599 

### What changed, and why?
Change all reference from "court_mandate" to "court_order".
Needed to change a small bit of Javascript so I could integrate my changes in the backend.

### How will this affect user permissions?
It will not.

### How is this tested? (please write tests!) 💖💪
I updated all the tests to work with the new names.

### Screenshots please :)
No visual changes, just a bunch of code in the back-end..

### CODE REVIEW

**Review by compwron — COMMENTED** [review]
This is good progress! 
Get the merge conflicts fixed and then let's merge this and open a new PR for the rest?

**Comment by efgalvao** [comment]
> This is good progress! Get the merge conflicts fixed and then let's merge this and open a new PR for the rest?

I`m going to change mandate_text in this pr too, https://github.com/rubyforgood/casa/issues/2599
Do you think it is better to separate ?

**Comment by efgalvao** [comment]
I will change the `mandate_text` to `order_text` in another pr, ok ?

**Review by FireLemons — CHANGES_REQUESTED** [review]

**Comment by compwron** [comment]
This PR is big and I want to get it merged. I think it's safe to merge except for the docx (and there should be a test for that...) Does that sound right @FireLemons ?

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
I really want to get this merged before power week starts- let's do the docx and additional renames in a following PR :)

**Comment by efgalvao** [comment]
@compwron I'm going to point my next PR to this one because I need these changes, Is ok for you ?

**Pull request merged**
