### PR TITLE
Trying different config for azure storage

### PR DESCRIPTION
**Pull request by pollygee**
@littleforest @compwron trying to figure out why azure isn't working.  Found this difference in the config file.  Hoping this change will fix it?

### CODE REVIEW

**Comment by pollygee** [comment]
I verified the env vars in heroku they are correct.  If this isn't the problem I'm not sure what next troubleshooting steps should be.

**Review by compwron — COMMENTED** [review]
lets try it! :)

**Comment by littleforest** [comment]
This can be named anything we want, but it has to match what we put in the production environment file:

https://github.com/rubyforgood/casa/blob/main/config/environments/production.rb#L43

**Comment by pollygee** [comment]
@littleforest oh ok I see.  I'll change it back.  Sorry about that.  
I don't know why it's not authenticating.

**Pull request merged**
