### PR TITLE
Issue2952/due date opt field

### LINKED ISSUE #2952: Make Court Report Due Date an Optional Field on all Court Dates
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently, we only have a Court Report Due Date for the next upcoming Court Date. 

1. We would like to add an optional field called "Court Report Due Date" to all court dates.
2. We would like to migrate currently set Court Report Due Dates so that they are attached to the next upcoming Court Date.
3.  We would like to remove the prompt to set a Court Report Due Date on the edit case details page. (See screenshot 1)
4. We want the Court Report Due Date to be settable when adding a Court Date. (See screenshot 2)
5. We want the Court Report Due Date to be settable when editing a Court Date. (See screenshot 3)
6. We want Court Report Due Date to be visible when viewing a Court Date. (See screenshot 4)

**Screenshots of current behavior, if any**  
Current location to set Court Report Due Date:
Court Report Due Date Current Location

Desired location to set Court Report Due Date:
Court Report Due Date Desired Location
and
Edit Court Date Page

Court Report Due Date Should Be Visible:
View Court Date

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by vasconsaurus**
### What GitHub issue is this PR for, if any?
Resolves #2952 

I started working on this, but I have a few questions. 
I'll start by answering the default questions and then go into my own.

### What changed, and why?
1. Removed the prompt to set a Court Report Due Date on the edit case details page
2. Added the input field to add a Court Report Due Date in the Court Dates' form (so we can set or edit a Court Report Due Date inside of Court Date)
3. Added Court Report Due Date to our Court Date show

### How will this affect user permissions?
- Volunteer permissions: shouldn't be able to set a Court Report Due Date
- Supervisor permissions: should be able to set a Court Report Due Date
- Admin permissions: should be able to set a Court Report Due Date

### How is this tested? (please write tests!) 💖💪
Since, I'm not quite sure about the changes yet, I haven't worked on the tests.
But I believe these are the relevant ones:
spec/system/casa_cases/edit_spec.rb (failures due to removed court report due date)
spec/system/casa_cases/new_spec.rb (failures due to removed court report due date)
spec/system/court_dates/edit_spec.rb (also fails)
spec/system/court_dates/new_spec.rb (fails: I changed the structure a bit, so it didn’t find the add button)
spec/views/casa_cases/ (all pass)
spec/views/court_dates/ (only show breaks)

### Screenshots please :)
1.
01 removed-details_page

2.
02 added-court_report_due_date_to_form

3.
03 added-court_report_due_date_to_court_dates

### My questions :)
1. I was a bit confused by this request: _2. We would like to migrate currently set Court Report Due Dates so that they are attached to the next upcoming Court Date._

This means instead of adding the Due Date as we were before, we should add one when creating a new Court Date, is this it?

2. I couldn't find a way to add a court date. I saw there was a hidden button. So I displayed it. Is this ok, or were you thinking about something else? (It does have a problem, that right now it also appears for the volunteers, and I think it shouldn't – if it's correct in the first place 😅 )

Screen Shot 2022-09-21 at 14 40 48

### CODE REVIEW

**Comment by compwron** [comment]
@FireLemons or @littleforest or I will take a look at this soon :)

**Comment by littleforest** [comment]
@vasconsaurus thanks so much for working on this! Because we are going to have a `court_report_due_date` for each court date, we will need to add a `court_report_due_date` field to the `court_dates` table. What do you think about this development flow?

1. Create new field `court_report_due_date` field on `court_dates` table
2. When creating or editing a court date, add an input field for this new `court_report_due_date` field.
3. Write an [after_party](https://github.com/theSteveMitchell/after_party) script that takes the current `court_report_due_date` on the `casa_cases` table and sets it as `court_report_due_date` on the `court_cases` record for the next upcoming court date.

Re the hidden button -- it doesn't look hidden on my view. Can you merge or rebase in the latest changes on the `main` branch? It's possible it was hidden for volunteers before, but now it is not:

Screen Shot 2022-09-30 at 1 49 02 PM

Let us know if you have any questions!

**Comment by vasconsaurus** [comment]
Hi @littleforest!

> Because we are going to have a court_report_due_date for each court date, we will need to add a court_report_due_date field to the court_dates table. 

What I had done was keep things as they were, but use `form fields` and `accepts_nested_attributes_for`to get around it. I think adding the `court_report_due_date` to `court_dates` does make more sense. Should we also keep this column on the `casa_case` table or remove it?

> Re the hidden button -- it doesn't look hidden on my view. Can you merge or rebase in the latest changes on the main branch? It's possible it was hidden for volunteers before, but now it is not

Yeah, I'm pretty sure it was hidden before, but it wasn't at the last office hours. There is always the possibility I got confused 😅

**Comment by littleforest** [comment]
Hi @vasconsaurus!

> What I had done was keep things as they were, but use form fields and accepts_nested_attributes_for to get around it

This will work if there is only one court date, but once you add a second court date, then when you save it will overwrite the `court_report_due_date` on the `casa_cases` table for that second court date and we will lose the information from the first `court_date`. So we will need a `court_report_due_date` on the `court_dates` table so we can be sure that each court date has its own `court_report_due_date`.

> Should we also keep this column on the casa_case table or remove it?

We should remove it in a later PR! You can create a follow-up ticket to remove the column. It can't be removed with this PR because then the column will get deleted before the data is transferred over to the `court_dates` table. We should probably keep the column around for a couple of weeks just to make sure we transitioned the old data correctly.

Let me know if you have any other questions!

**Comment by vasconsaurus** [comment]
Hi @littleforest, another question:
`casa_case` has only one `court_report_due_date`, but can have many `court_dates`.  Should I move the `court_report_due_date` to all `court_dates` or only to the last one (here I'm inferring the `court_report_due_date` was updated as a new `court_date` was created, so it only relates to the last one)?

**Review by compwron — APPROVED** [review]
looks good! :)

**Comment by compwron** [comment]
✨

**Comment by littleforest** [comment]
Great job @vasconsaurus

**Pull request merged**
