### PR TITLE
Setting case contact occurred date to current date when a future date…

### LINKED ISSUE #2533: Reset Date to Current Date When Set to Future Date on Case Contact
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently, if you try to set the Occurred at date on a Case Contact to a date in the future, a warning flashes on the screen, but the date does not change to a different date. We would like it if when this warning flashes the date would be set back to the current date. 

**Screenshots of current behavior, if any**  
Case Contacts Shouldn't Occur in the Future

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

### PR DESCRIPTION
**Pull request by arthur1041**
### What github issue is this PR for, if any?
Resolves #2533

### What changed, and why?
When a future date was set to the case contact occurred date, a alert was showed informing that it is not possible to set a future date, but the date in the date input field was not being set back to the current date.
My modification adds a new feature, that is to set the occured date to the current date when the scenary described above happens.

### How will this affect user permissions?
- Volunteer permissions: doesn't affect
- Supervisor permissions: doesn't affect
- Admin permissions: doesn't affect

### How is this tested? (please write tests!) 💖💪
Just run the already existing tests in the project. As the modifications were simple and short JavaScript modificaitions, no new tests were needed to be written.

### Screenshots please :)
ezgif com-gif-maker

### CODE REVIEW

**Review by compwron — APPROVED** [review]
great! :)
I would like to also have a test about this- maybe a jest test?

**Comment by arthur1041** [comment]
> @github-actions

I'll write it.

**Comment by arthur1041** [comment]
> great! :) I would like to also have a test about this- maybe a jest test?



> great! :) I would like to also have a test about this- maybe a jest test?

I'll write it.

**Comment by arthur1041** [comment]
@compwron just added both jest and rspec tests to my branch.

**Review by ghost — APPROVED** [review]

**Comment by compwron** [comment]
@[arthur1041](https://github.com/arthur1041) that sounds like a good lint fix in a separate PR!

**Comment by arthur1041** [comment]
> @[arthur1041](https://github.com/arthur1041) that sounds like a good lint fix in a separate PR!

Okay! So I'll open a new issue requesting this fix.

**Pull request merged**
