### PR TITLE
Fix misspellings in document

### PR DESCRIPTION
**Pull request by aisayo**
I found a few misspelled words in this document. Submitting a fix

### CODE REVIEW

**Comment by Anirudha-JN** [comment]
heyy I would like to work on this issue, please assign me this issue

**Comment by fbuys** [comment]
> heyy I would like to work on this issue, please assign me this issue

I think this PR already addresses the issue. Or which issue are you referring to @Anirudha-JN ?

**Comment by Anirudha-JN** [comment]
[Fix misspellings in document] this issue

**Review by littleforest — APPROVED** [review]
Thanks for catching these.

**Pull request merged**
