### PR TITLE
[#2507] [WIP] All contact types are checked by default. Added buttons to uncheck or…

### LINKED ISSUE #2507: Make Contact Types All Checked By Default on Edit Case Details Page
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Currently, on the Edit Case Details page, all the boxes under contact types are unchecked by default. We would like all of these boxes to be checked by default instead. Also we would like to add two buttons, one which checks all the boxes, and one which unchecks all of the boxes. Finally, we would like all the boxes being unchecked to prevent the page from being saved, with a message pop up that says, "At least one contact type must be selected.".

There is another ticket relating to the layout of this page, which may be relevant: https://github.com/rubyforgood/casa/issues/2505

**Screenshots of current behavior, if any**  
Contact Types in Edit Case Details

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

### PR DESCRIPTION
**Pull request by nehaabraham**
… check all contact types. Cases do not save unless at least one contact type is selected

### What github issue is this PR for, if any?
Resolves #2507

### What changed, and why?
All contact types are checked by default. Added buttons to uncheck or check all contact types. Cases do not save unless at least one contact type is selected

### How will this affect user permissions?
- Volunteer permissions: not affected
- Supervisor permissions: not affected
- Admin permissions: not affected

### How is this tested? (please write tests!) 💖💪
Casa cases will return an error message when trying to save without any contact types selected. Casa cases will save when one or more contact types are selected. If a case has no contact types selected, the edit form will select all contact types by default. 

### Screenshots please :)

Screen Shot 2021-10-12 at 11 52 24 AM (2)
Screen Shot 2021-10-12 at 11 52 26 AM (2)
Screen Shot 2021-10-12 at 11 52 30 AM (2)
Screen Shot 2021-10-12 at 11 52 38 AM (2)

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by nehaabraham** [comment]
Working on specs

**Comment by compwron** [comment]
@nehaabraham if you want to work together on this, I'm happy to talk in slack #casa or set up some time
If not no worries, someone can adopt this if you're busy - just let me know :)

**Comment by compwron** [comment]
@nehaabraham I would love to merge this if you have time to finish it :)

**Comment by compwron** [comment]
failing tests

rspec ./spec/system/casa_cases/new_spec.rb:49 # casa_cases/new when non-mandatory fields are not filled is successful
rspec ./spec/system/casa_cases/new_spec.rb:18 # casa_cases/new when all fields are filled is successful
rspec ./spec/lib/importers/case_importer_spec.rb:50 # CaseImporter#import_cases returns a success message with the number of cases imported
rspec ./spec/lib/importers/case_importer_spec.rb:57 # CaseImporter#import_cases static and instance methods have identical results
rspec ./spec/lib/importers/case_importer_spec.rb:17 # CaseImporter#import_cases imports cases and associates volunteers with them
rspec ./spec/lib/importers/case_importer_spec.rb:80 # CaseImporter#import_cases when there's no case number returns an error message if row does not contain a case number
rspec ./spec/system/casa_cases/edit_spec.rb:25 # Edit CASA Case logged in as admin edits case
rspec ./spec/system/casa_cases/edit_spec.rb:503 # Edit CASA Case logged in as volunteer edits case
rspec ./spec/views/casa_cases/new.html.erb_spec.rb:22 # casa_cases/new while signed in as admin 
rspec ./spec/views/casa_cases/new.html.erb_spec.rb:32 # casa_cases/new while signed in as supervisor 
rspec ./spec/views/casa_cases/new.html.erb_spec.rb:33 # casa_cases/new while signed in as supervisor 
rspec ./spec/requests/casa_cases_spec.rb:576 # /casa_cases as a supervisor PATCH /update with valid parameters also responds as json
rspec ./spec/requests/casa_cases_spec.rb:571 # /casa_cases as a supervisor PATCH /update with valid parameters redirects to the casa_case
rspec ./spec/requests/casa_cases_spec.rb:557 # /casa_cases as a supervisor PATCH /update with valid parameters updates fields (except case_number)
rspec ./spec/requests/casa_cases_spec.rb:124 # /casa_cases as an admin POST /create only creates cases within user's organizations
rspec ./spec/requests/casa_cases_spec.rb:170 # /casa_cases as an admin POST /create invalid request with case_court_orders_attributes being passed as a parameter Creates a new CasaCase, but no CaseCourtOrder
rspec ./spec/requests/casa_cases_spec.rb:154 # /casa_cases as an admin POST /create invalid request with invalid parameters also respond to json
rspec ./spec/requests/casa_cases_spec.rb:106 # /casa_cases as an admin POST /create with valid parameters sets fields correctly
rspec ./spec/requests/casa_cases_spec.rb:115 # /casa_cases as an admin POST /create with valid parameters also responds as json
rspec ./spec/requests/casa_cases_spec.rb:101 # /casa_cases as an admin POST /create with valid parameters redirects to the created casa_case
rspec ./spec/requests/casa_cases_spec.rb:94 # /casa_cases as an admin POST /create with valid parameters creates a new CasaCase
rspec ./spec/requests/casa_cases_spec.rb:278 # /casa_cases as an admin PATCH /update court orders when the user tries to make an existing order empty does not update the second court order
rspec ./spec/requests/casa_cases_spec.rb:272 # /casa_cases as an admin PATCH /update court orders when the user tries to make an existing order empty does not update the first court order
rspec ./spec/requests/casa_cases_spec.rb:213 # /casa_cases as an admin PATCH /update with valid parameters redirects to the casa_case
rspec ./spec/requests/casa_cases_spec.rb:201 # /casa_cases as an admin PATCH /update with valid parameters updates the requested casa_case
rspec ./spec/requests/casa_cases_spec.rb:224 # /casa_cases as an admin PATCH /update with valid parameters also responds as json
rspec ./spec/requests/casa_cases_spec.rb:219 # /casa_cases as an admin PATCH /update with valid parameters displays changed attributes
rspec ./spec/requests/casa_cases_spec.rb:471 # /casa_cases as a volunteer PATCH /update with valid parameters also responds as json
rspec ./spec/requests/casa_cases_spec.rb:453 # /casa_cases as a volunteer PATCH /update with valid parameters updates permitted fields
rspec ./spec/requests/casa_cases_spec.rb:466 # /casa_cases as a volunteer PATCH /update with valid parameters redirects to the casa_case
rspec ./spec/controllers/case_contacts_controller_spec.rb:42 # CaseContactsController GET new when the case does not have specific contact types assigned assigns all the organizations contact type groups to @current_organization_groups
rspec ./spec/controllers/case_contacts_controller_spec.rb:47 # CaseContactsController GET new when the case does not have specific contact types assigned calls contact_types_alphabetically
rspec ./spec/lib/tasks/data_post_processors/case_contact_populator_spec.rb:43 # CaseContactPopulator creates a new contact type with the org of the casa case
rspec ./spec/lib/tasks/data_post_processors/case_contact_populator_spec.rb:16 # CaseContactPopulator does nothing if there are no contact types
rspec ./spec/lib/tasks/data_post_processors/case_contact_populator_spec.rb:26 # CaseContactPopulator creates a new contact type group with the org of the casa case
rspec ./spec/system/case_contacts/new_spec.rb:49 # case_contacts/new when admin should display full text in table if notes are less than 100 characters
rspec ./spec/system/case_contacts/new_spec.rb:8 # case_contacts/new when admin does not display empty or hidden contact type groups; can create CaseContact
rspec ./spec/system/case_contacts/new_spec.rb:83 # case_contacts/new when admin should allow expanding or hiding if notes are more than 100 characters
rspec ./spec/system/case_contacts/new_spec.rb:130 # case_contacts/new when admin with invalid inputs does not submit the form
rspec ./spec/system/case_contacts/new_spec.rb:158 # case_contacts/new when admin with HTML in notes renders HTML correctly on the index page
rspec ./spec/system/case_contacts/new_spec.rb:281 # case_contacts/new volunteer user autosaves notes
rspec ./spec/system/case_contacts/new_spec.rb:368 # case_contacts/new volunteer user submits the form when note is added and confirmed
rspec ./spec/system/case_contacts/new_spec.rb:339 # case_contacts/new volunteer user submits the form when no note was added
rspec ./spec/system/case_contacts/new_spec.rb:399 # case_contacts/new volunteer user does not submit the form when note is added but not confirmed
rspec ./spec/system/case_contacts/new_spec.rb:238 # case_contacts/new volunteer user is successful
rspec ./spec/system/case_contacts/new_spec.rb:482 # case_contacts/new volunteer user with contact made not checked does not re-render form, preserves all previously entered selections
rspec ./spec/system/case_contacts/new_spec.rb:429 # case_contacts/new volunteer user with invalid inputs re-renders the form with errors, but preserving all previously entered selections
rspec ./spec/requests/imports_spec.rb:125 # /imports GET /index creates case in cases CSV imports

**Comment by compwron** [comment]
I am closing this for now, we will let someone start over fresh :)

**Pull request closed without merging**
