### PR TITLE
add lock icons

### LINKED ISSUE #4666: Ability to lock cases for case contacts
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
 - Remove autosaving of checked cases from the case contact form autosaver
 - For each casa case listed at the top of the new case contact form, put a lock button on the right
 - The lock button will
    - have an unlocked icon by default
    - toggle between a locked and unlocked icon when clicked
    - disable the checkbox left of it when in locked mode
    - make the checkbox checked in locked mode
 - The locked state will not change until the user toggles the lock
 - Write System Tests

Kind of like this but make the buttons line up
image

**Screenshots of current behavior**  
image

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by dominiclizarraga**
### What github issue is this PR for, if any?
Resolves #4666

@FireLemons sorry for being late. Please see my notes and the video i attached.

- Just rebased new theme I think so far. I did followed [rebase guidelines](https://rubyforgood.slack.com/archives/CVB0QJGVD/p1679764917656569)

- `yarn lint:fix ` is done as well.

- The lock icon is on the right of the casa case.

### What changed, and why?

Lock icons on casa-case were added. 🔒 🔓

### How will this affect user permissions?
- Volunteer permissions: n/a
- Supervisor permissions: n/a
- Admin permissions: n/a

### How is this tested? (please write tests!) 💖💪

Testing is not ready yet

### Screenshots please :)

https://github.com/rubyforgood/casa/assets/70678718/a9c9bd77-8a69-40b3-8eda-c017d7abacec

### CODE REVIEW

**Review by littleforest — COMMENTED** [review]
@dominiclizarraga thanks so much for working on this! Could you please add some system tests that show that locking the case does not save changes to the record (and vice-versa)?

**Comment by littleforest** [comment]
Here is the CodeClimate error. If possible to fix, that would be great, otherwise we don't have to worry about it:

Screen Shot 2023-05-13 at 10 48 57 AM

**Comment by FireLemons** [comment]
The state of the lock has to only change when a user toggles it. I didn't describe that well in the issue. I updated the issue. The lock doesn't stay if the case contact form is submitted.

**Comment by dominiclizarraga** [comment]
- [ ] Move the lock to the left of the checkbox.
- [ ] Disable the checkbox left of it when in locked mode.
- [ ] Testing (that show that locking the case does not save changes to the record (and vice-versa)).
- [ ] Load function exceeds 25 lines.

**Comment by dominiclizarraga** [comment]
- [ ]  Testing (that show that locking the case does not save changes to the record (and vice-versa)).

@FireLemons I'm not sure how to write the tests for this case since the locked state isn't an attribute of an object on the backend as we only persist it to local storage. Any pointers on how to proceed would be great!

**Comment by dominiclizarraga** [comment]
- [ ] For testing we are good with Capybara since it's just browser manipulation.

- [ ] Once a case is submitted and we create a new case the form must remember the checkboxes that were either checked or unchecked (currently it restarts, not recall prior state).

**Comment by littleforest** [comment]
@dominiclizarraga yes, some system specs using Capybara would be great!

**Comment by compwron** [comment]
Please rebase and that should fix CI

**Comment by dominiclizarraga** [comment]
@FireLemons @compwron I tried to make the capybara test but somehow the browser doesn't display the `i tag` therefore it doesn't disable the `input`, it seems that assets are not being loaded.

Any clue what can it be?

Screenshot 2023-05-31 at 5 23 06 PM

**Comment by dominiclizarraga** [comment]
@FireLemons there's one failing text however I didn't touch it ☹️

**Comment by littleforest** [comment]
@dominiclizarraga would you mind fixing merge conflicts? Let's see if we can get this merged in.

**Comment by FireLemons** [comment]
1. Update the branch
2. move lock javascript code out of [case_contact_autosave.js](https://github.com/rubyforgood/casa/pull/4814/files#diff-3dd7c25b3df947ec30b17fbae5e138d58db53ee719daf36a30e5ecb2d6db0003) into own file

**Pull request closed without merging**
