### PR TITLE
[WIP] Fix Add Language error on empty language

### LINKED ISSUE #3960: Bug: Clicking add for second languages without selecting a language as a volunteer leads to a 404
### Impacted User Types
 - volunteers

### Current Behavior
Clicking add for second languages without selecting a language as a volunteer leads to a 404
image
image

### Expected Behavior
An error like this one is shown when no language is selected and the form is submitted
image

### How to Replicate
ex: 
1. - Log in as a volunteer
2. - Click on "Edit Profile" in the left sidebar menu.
image
4. - Scroll down and click on Add without selecting a language
image

### Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by elhalvers**
### What github issue is this PR for, if any?
Resolves #3960

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by elhalvers** [comment]
Current behavior: When using the 'Add language' drop-down on the 'Edit User's Profile' page logged in as a Volunteer:
 - Adding a specific language works as expected
 - Deleting a specific language works as expected
 - Adding a 'blank' language (default from the _languages partial in the Users folder) does not break the page as it did before but also does not yet provide an error message alerting the user that they can not choose a 'blank' language.

**Comment by compwron** [comment]
How's this going? It looks promising! :)

**Comment by elhalvers** [comment]
Hi! Good!

The functionality for the issue is currently working as expected. Because
we also moved a method from the languages_controller to the
users_controller we are having to write/rewrite/modify a lot of tests.
There is a counterpart method that will need to be moved as well to match.
(add_language, remove_language). We added a new issue for this. #4079.

So, although the behavior is correct when testing manually, the testing is
not complete.

: )

**Comment by elhalvers** [comment]
All the checks pass. I need to finish the stubbed tests 🙂

**Comment by compwron** [comment]
:)

**Review by compwron — APPROVED** [review]

**Comment by elhalvers** [comment]
Thank you!

: )

Eric

**Pull request merged**
