### PR TITLE
Disable form for unassigned volunteers

### LINKED ISSUE #3111: Disable interactive form elements when there are no eligible volunteers for assignment
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
Disable the dropdown and the assign volunteer button

**Screenshots of current behavior, if any**  
image

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by soc-man**
### What github issue is this PR for, if any?
Resolves #3111

### What changed, and why?
Disabled the drop-down and "assign volunteer' button when there are no volunteers available.

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by soc-man** [comment]
I believe I've worked on this issue, might need help with testing if any :) Thanks

**Comment by compwron** [comment]
Hi! Your build is failing, please take a look at the failing tests :)

**Comment by compwron** [comment]
You can click on the red X to see the failing test. The red link takes you to https://github.com/rubyforgood/casa/runs/4985928176?check_suite_focus=true which says 
```
  1) supervisors/edit logged in as a supervisor when editing own page when no volunteers exist does not error out when adding non-existent volunteer
     Failure/Error: click_on "Assign Volunteer"

     Capybara::ElementNotFound:
       Unable to find link or button "Assign Volunteer"
     # ./spec/system/supervisors/edit_spec.rb:224:in `block (5 levels) in <top (required)>'

Finished in 6 minutes 55 seconds (files took 9.27 seconds to load)
1634 examples, 1 failure, 8 pending

Failed examples:

rspec ./spec/system/supervisors/edit_spec.rb:221 # supervisors/edit logged in as a supervisor when editing own page when no volunteers exist does not error out when adding non-existent volunteer
```

Which is related to your work.

**Comment by soc-man** [comment]
Thanks @compwron working on this

**Comment by compwron** [comment]
Getting closer! Try running the failing test on your local machine to see what it does
(copied from CI github actions output)
```
  1) supervisors/edit logged in as a supervisor when editing own page when no volunteers exist does not error out when adding non-existent volunteer
     Failure/Error: click_on "Assign Volunteer"

     Capybara::ElementNotFound:
       Unable to find visible link or button "Assign Volunteer"
     # ./spec/system/supervisors/edit_spec.rb:224:in `block (5 levels) in <top (required)>'

Finished in 6 minutes 56 seconds (files took 9.93 seconds to load)
1640 examples, 1 failure, 8 pending

Failed examples:

rspec ./spec/system/supervisors/edit_spec.rb:221 # supervisors/edit logged in as a supervisor when editing own page when no volunteers exist does not error out when adding non-existent volunteer
```

**Comment by soc-man** [comment]
Hi @compwron i noticed in the ./spec/system/supervisors/edit_spec.rb file, line 223 and 224 are exactly the same, could that be the reason the test is failing?

**Comment by compwron** [comment]
> spec/system/supervisors/edit_spec.rb

@soc-man the test is intentionally trying to assign a volunteer when there are no volunteers left to assign, so the test is correct for the old behavior of the code. But you have changed the behavior of the code, so you need to update the code to match the new code. :)

**Comment by compwron** [comment]
I ran the code locally and here is a screenshot. (Next time please include a screenshot in the pull request description) It looks a little funny that might be pre-existing and we can make a separate issue for it
Screen Shot 2022-02-01 at 8 46 58 PM

**Comment by compwron** [comment]
I removed the extra border with https://getbootstrap.com/docs/4.0/utilities/borders/ :)
Screen Shot 2022-02-01 at 8 58 23 PM

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
🎉 🎉 🎉

**Comment by compwron** [comment]
Thank you and congrats on your first CASA pull request! Feel free to pick another issue to work on or let me know if you want help picking an issue :)

**Comment by soc-man** [comment]
@compwron thanks for the help, I should polish up on testing :) And it was fun I got to learn some new things. Will for sure contribute again. Thanks!

**Pull request merged**
