### PR TITLE
[878] Fixes various UI issues

### LINKED ISSUE #878: broken login screen layout on qa
**Environment**
qa https://casa-qa.herokuapp.com/

**What's broken**
- image is cut off
- email and password text fields are too short
- page should not have so much blank space on the left
- sidebar should be on the left side (although I think it might be gone entirely in the new login screen mockup)

**Screenshots of current behavior**
Screen Shot 2020-09-25 at 4 02 56 PM

### PR DESCRIPTION
**Pull request by drborges**
### What github issue is this PR for, if any?

Resolves #878 

### What changed, and why?

Fixes a few alignment and page scrolling issues:

### 1. Broken alignment of page header and footer on login page:

Before:

Screen Shot 2020-09-25 at 10 08 35 PM

After:

Screen Shot 2020-09-25 at 8 54 22 PM

### 2. Broken sidebar menu items for all casa admins:

Before:

Screen Shot 2020-09-25 at 10 05 35 PM

After:

Screen Shot 2020-09-25 at 10 07 45 PM

### 3. Scrolling issues on mobile view:

Before:

mobile-scroll-issue-before

After:

### 4. Sidebar is not scrollable (admins for instance can't get to log out link on smaller viewports):

Before:

After:

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### CODE REVIEW

**Review by ds29 — APPROVED** [review]
Thank you for this!

**Comment by Zrrrpy** [comment]
This looks great @drborges - and nothing breaks when you change the size of the main login screen?

**Comment by drborges** [comment]
@Zrrrpy you were right, the UI looked a little off on a mobile version and the all casa admin login page was messed up as well. I'll work on a fix for these latest issues and post a few more GIFs. I think that there's still room for improvement but It might be better to wait for @jasperfurniss's new login page implementation which should take care of all issues that I ran into (pretty much around responsive layout).

**Comment by Zrrrpy** [comment]
agreed @drborges – @jasperfurniss do you feel good about us holding on further changes and instead waiting on the new login page implementation to be ready?

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
:) :) :)

**Comment by compwron** [comment]
You are invited to the CASA asynchronous retrospective-and-futurespective! Please take a look at https://bit.ly/casaretro (no login required) and add at least one note! Even if it's just "I was here and you are cool" or "omg y'all why do you keep messaging me" we want to hear it. <3
Next week Wednesday 18 November @ 6pm Pacific time we will Zoom about the board and talk about themes and takeaways. (Zoom link in our calendar at http://bit.ly/casacal or slack #casa channel https://rubyforgood.herokuapp.com/ )
Please ESPECIALLY add lots of notes if you won't be able to make it on Wednesday to talk!
* Note: the board will be monitored for spam; message me or any team lead if you see a problem
https://bit.ly/casaretro

**Pull request merged**
