### PR TITLE
Fix simplecov and Code Climate Test Reporter

### LINKED ISSUE #1040: Publish test coverage data to codeclimate
**Description**
Publish test coverage data to codeclimate
https://codeclimate.com/github/rubyforgood/casa/progress/coverage
https://docs.codeclimate.com/docs/configuring-test-coverage

**Screenshots of current behavior, if any**
Screen Shot 2020-10-11 at 10 42 34 AM

### PR DESCRIPTION
**Pull request by cassianoblonski**
### What github issue is this PR for, if any?
Resolves #1040 

### What changed, and why?
Simplecov version, after some time searching and looking at the errors and logs on Travis and checking the configuration for the test reporter I found a problem with simplecov 0.18+ and CodeClimate Test Reporter, some changes in simplecov 0.18 are not compatible with the actual CodeClimate Test Reporter, to make it work together I fixed the version of simplecov to 0.17.1, as stated on the issue https://github.com/codeclimate/test-reporter/issues/418 CodeClimate core team is trying to work with simplecov to make 0.18 compatible with test reporter.

### What is still needed?
I need someone with permission to edit the settings on this repo to add an env var called `CC_TEST_REPORTER_ID` with the CodeClimamte Test Reporter ID, that can be achieved similar to the example below:
image

### Screenshots please :)
_**note that I tested the screenshots below with the current `CC_TEST_REPORTER_ID` on the travis.yml, we need to check if this ID is the correct one and add it to the repo env var on Repo Settings as stated above.**_

before:
image

after:
image

at the moment, waiting for the repo env var:
image

### CODE REVIEW

**Comment by cassianoblonski** [comment]
@compwron can you edit the Repo Settings and add the env var listed on the description or ask someone with the permissions to do this.

**Review by compwron — APPROVED** [review]
:)

**Comment by compwron** [comment]
Screen Shot 2020-10-21 at 12 23 42 AM

**Comment by compwron** [comment]
thanks!

**Pull request merged**
