### PR TITLE
2409 update change password flow

### LINKED ISSUE #2409: Make Change Password Flow Easier to Understand and More Secure
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently, the change password page has two fields labelled Password and Password Confirmation. When matching information is typed into both fields, and that information conforms to the password requirements, the password is changed to whatever was entered. 

We would like it to have three fields, one which accepts and verifies the current password, labelled Current Password, and the existing two fields with the labels changed to New Password and New Password Confirmation respectively. We would like the current password entered to have to be correct for the password to be changed, and the rest of the password flow to continue working as it does (i.e. the two inputs in New Password and New Password Confirmation must match, and conform to the password requirements in order for the password to be changed to what is entered in the New Password fields). 

**Screenshots of current behavior, if any**  
Screen Shot 2021-08-13 at 6 43 37 PM

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456

### PR DESCRIPTION
**Pull request by codewithjulie**
### What github issue is this PR for, if any?
Resolves #2409 

### What changed, and why?
Add current password field for users wishing to update their password for added security. 

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### How is this tested? (please write tests!) 💖💪
```
it "displays password errors messages when user is unable to set a password with incorrect current password" do
      click_on "Change Password"

      fill_in "Current Password", with: "12345"
      fill_in "New Password", with: "1234567"
      fill_in "New Password Confirmation", with: "1234567"

      click_on "Update Password"

      expect(page).to have_text("Current password is incorrect")
    end

    it "displays password errors messages when user is unable to set a password" do
      click_on "Change Password"

      fill_in "Current Password", with: "123456"
      fill_in "New Password", with: "123"
      fill_in "New Password Confirmation", with: "1234"

      click_on "Update Password"

      expect(page).to have_text("Password confirmation doesn't match Password")
      expect(page).to have_text("Password is too short (minimum is 6 characters)")
    end

    it "notifies a user when they update their password" do
      click_on "Change Password"

      fill_in "Current Password", with: "123456"
      fill_in "New Password", with: "1234567"
      fill_in "New Password Confirmation", with: "1234567"

      click_on "Update Password"

      expect(page).to have_text("Password was successfully updated.")
    end
```

### Screenshots please :)
Screen Shot 2021-09-01 at 7 56 00 PM
Screen Shot 2021-09-01 at 7 56 25 PM

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### CODE REVIEW

**Review by compwron — APPROVED** [review]
Very nice!!! :)

**Comment by compwron** [comment]
@codewithjulie feel free to merge as soon as you've resolved the merge conflict :)

**Comment by codewithjulie** [comment]
Had to fix some failing tests, just making sure you had visibility and that it is okay before merging @compwron

**Comment by compwron** [comment]
Woot woot WOOT, very cool! :) :) :)

**Pull request merged**
