### PR TITLE
Refactoring README, adding links to Linux and Mac OS instructions

### LINKED ISSUE #649: README Refactoring to Better Separate OS-specific from OS-agnostic information
**Description**

I wrote up the LINUX_SETUP.md file but forgot to refer to it in README.md, so someone reading there for instructions for installing on a Linux host may never find out that there are more detailed instructions for them there. Since there is also a Docker instruction file, I suggest we remove the remaining Linux and Docker information from README.md, and move the Mac OS instructions to a new file (maybe MAC_OS.md), and refer and link to the three of them similarly in README.md.

**Existing file(s) needing changing**
README.md

**New file(s) needing creating**
MAC_OS.md

### PR DESCRIPTION
**Pull request by talentedunicorn**
### What github issue is this PR for, if any?
Resolves #649 

### What changed, and why?
Added links to LINUX_SETUP.md on README.md to improve documentation for Linux users.
Added MAC_OS.md for setup instructions for Mac OS users.

### How will this affect user permissions?
- Volunteer permissions: N/A
- Supervisor permissions: N/A
- Admin permissions: N/A

### How is this tested? (please write tests!) 💖💪
N/A

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### CODE REVIEW

**Comment by talentedunicorn** [comment]
@keithrbennett i'm almost done with this PR but i'm not sure which part of the README is _specific_ instructions for Mac OS

**Comment by keithrbennett** [comment]
This issue is a lot more complex than it appears at first glance, and it requires a lot of detail orientation and patience (which is why I have not addressed the issue yet myself). The meat of this issue is studying the text, extracting, clarifying, and sometimes copying. It is not a simple cut and paste; there are some references to specific OS's, and some to multiple; OS-specific content needs to be extracted, but without resulting in omissions of important information for other OS's. I see that you are a front end developer; would you like to address a front end issue instead?

**Comment by talentedunicorn** [comment]
> This issue is a lot more complex than it appears at first glance, and it requires a lot of detail orientation and patience (which is why I have not addressed the issue yet myself). The meat of this issue is studying the text, extracting, clarifying, and sometimes copying. It is not a simple cut and paste; there are some references to specific OS's, and some to multiple; OS-specific content needs to be extracted, but without resulting in omissions of important information for other OS's. I see that you are a front end developer; would you like to address a front end issue instead?

I see, sure thing i'd like to take on a front end issue

**Comment by jmkoni** [comment]
@talentedunicorn look around, but maybe consider this one? 
https://github.com/rubyforgood/casa/issues/771

**Comment by jmkoni** [comment]
I’m gonna go ahead and close this

**Comment by keithrbennett** [comment]
Why did you close this? I was intending to get around to it some time if no one else beat me to it.

**Pull request closed without merging**
