### PR TITLE
Rake task to send emancipation checklist reminder notification

### LINKED ISSUE #2783: Send Monthly Notifications Reminding Volunteers to Use Emancipation Checklist
**What type(s) of user does this feature affect?**
 - volunteers

**Description**
Currently there is no system in place to remind volunteers with transition aged youth to utilize the Emancipation Checklist. We would like to add a system that sends a Notification (like those sent when there is a request for follow up on a case contact) on the first of each month to volunteers who are handling at least one case with a transition aged youth. We would like this notification to read "Your case <Case Number> is a transition aged youth. We want to make sure that along the way, we’re preparing our youth for emancipation. Make sure to check the emancipation checklist: <link>". The link should take the volunteer directly to the emancipation checklist for their transition aged youth. In the case that the volunteer has multiple transition aged youth they should get a notification for each case, with each link going to the checklist appropriate to the case number listed in the notification.  

**Screenshots of current behavior, if any**  
An example view of the notifications page where we want this message to appear:
Notifications Page

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by librod89**
### What github issue is this PR for, if any?
Resolves #2783

### What changed, and why?
- Create new notification to remind volunteers to use the Emancipation Checklist
- Create new rake task to send notification (this needs to be scheduled in heroku to run once per month)

### How will this affect user permissions?
N/A

### How is this tested? (please write tests!) 💖💪
New test for the rake task

### Screenshots please :)
image

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by librod89** [comment]
@compwron, if I'm understanding the code correctly, `transition_aged_youth` cases are ones with birthdates greater than 14 years. So the volunteer will get these notifications forever once the case has transitioned. Is there another check (like if the case is active) that this rake task should check for so the notifications end at some point?

**Comment by compwron** [comment]
It seems correct to notify the volunteer once per month about the checklist while they are actively assigned to a transition aged youth. https://github.com/rubyforgood/casa/pull/4030#issuecomment-1272093325 :)

**Review by littleforest — COMMENTED** [review]
This looks good to me, but I haven't played much with the notifications. When they click the notification, it will take them to the `casa_case_emancipation_path(params[:casa_case].id)` url?

**Comment by librod89** [comment]
> This looks good to me, but I haven't played much with the notifications. When they click the notification, it will take them to the `casa_case_emancipation_path(params[:casa_case].id)` url?

Yep! I also verified that when multiple notifications are sent to a volunteer, each notification click navigates to the correct case specific emancipation checklist.

**Review by littleforest — APPROVED** [review]
🎉

**Comment by librod89** [comment]
@littleforest or @compwron do one of you have access to heroku scheduler so this task can get scheduled to run once per month?

**Comment by littleforest** [comment]
@librod89 yes, I will add it now! Thanks for the reminder :)

**Comment by littleforest** [comment]
@librod89 the minimum we can run tasks is daily. Will it hurt to run this task everyday, or should we modify the task to check the date and only run it if the current day == 1 or something like that?

**Comment by librod89** [comment]
Oh the `youth_birthday_reminder` task has a comment saying it's run every 15th of the month so I thought this was possible. If not, we definitely shouldn't run this task every day. I can update it to check the date somehow.

**Pull request merged**
