### PR TITLE
Add birthdate for CasaCase examples in seed

### LINKED ISSUE #2342: Add Birthdate for Test Casa Cases
**Description**
Test casa cases are generated without birthdays

see `db/seeds/db_populator.rb`

### PR DESCRIPTION
**Pull request by m-pereira**
Resolves #2342

### Overview

Add `birth_month_year_youth` attribute, for `CasaCase` examples in seed.

### How is this tested? (please write tests!) 💖💪

Just running `bin/rails db:seed:replant`

### CODE REVIEW

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
Very cool :)

**Comment by FireLemons** [comment]
The range of these could be better

birth_month_year_youth: Wed, 10 Nov 2021 00:00:00.000000000 UTC +00:00,
This one occurs in the future

birth_month_year_youth: Thu, 03 Jun 2021 00:00:00.000000000 UTC +00:00,
When a youth hits 14 years of age they are transitioning to adulthood. It would be nice to have a few that are between 14 to I think 18 years of age. 

Please make them 4 to 18 years of age.

**Review by FireLemons — CHANGES_REQUESTED** [review]
Please make the kids 4 to 18 years old randomly and guarantee that 2 are over 14 years old

**Comment by m-pereira** [comment]
> Please make the kids 4 to 18 years old randomly and guarantee that 2 are over 14 years old

After apply the fixes:

```rb
irb(main):001:0> CasaCase.pluck(:birth_month_year_youth).map { |date| I18n.l(date)  }
   (0.5ms)  SELECT "casa_cases"."birth_month_year_youth" FROM "casa_cases"
=> 
["Fri, 09 Apr 2010 00:00:00 +0000",
 "Mon, 16 May 2011 00:00:00 +0000",
 "Wed, 30 Sep 2015 00:00:00 +0000",
 "Tue, 17 Jul 2012 00:00:00 +0000",
 "Thu, 18 Jul 2013 00:00:00 +0000",
 "Sat, 16 Mar 2013 00:00:00 +0000",
 "Thu, 14 Jun 2007 00:00:00 +0000",
 "Sun, 03 Jun 2007 00:00:00 +0000",
 "Wed, 12 Jul 2006 00:00:00 +0000",
 "Fri, 20 Apr 2007 00:00:00 +0000",
 "Tue, 22 Jun 2004 00:00:00 +0000"]
 ```
```rb
irb(main):002:0> CasaCase.where('birth_month_year_youth <= ?', Date.today - 14.years).count
   (1.6ms)  SELECT COUNT(*) FROM "casa_cases" WHERE (birth_month_year_youth <= '2007-08-08')
=> 5
```

**Review by FireLemons — APPROVED** [review]

**Comment by FireLemons** [comment]
The changes you've made have broken some tests  
It seems like the casa_org is set incorrectly for some or all casa_cases  
  
`Volunteer and case must belong to the same organization`

see `spec/seeds/seeds_spec.rb`

**Comment by compwron** [comment]
It is looking good! Let's get the tests fixed and then we can merge :)

**Comment by m-pereira** [comment]
> The changes you've made have broken some tests
> It seems like the casa_org is set incorrectly for some or all casa_cases
> 
> `Volunteer and case must belong to the same organization`
> 
> see `spec/seeds/seeds_spec.rb` around line 32

Locally the spec doesn't fail. I've just re-run it. About docker one, I need some help to fix that.

**Comment by FireLemons** [comment]
looks good to me. I don't think the docker failures are related to your code changes.

**Comment by FireLemons** [comment]
:1st_place_medal:

**Pull request merged**
