### PR TITLE
Issue#2698 persist column visibility state stage 1 migration and user callback

### LINKED ISSUE #2698: Allow Users to Save Column Display Preferences
**What type(s) of user does this feature affect?**
 - supervisors
 - admins

**Description**
On the combined cases and volunteers page (see: https://github.com/rubyforgood/casa/issues/2694) we would like to make it possible for users to save their preferences regarding which columns to show and which to hide in the table. 

**Screenshots of current behavior, if any**  
The Current Select Displayed Columns Pop-up:
Select Columns Popup

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

### PR DESCRIPTION
**Pull request by GALTdea**
### What github issue is this PR for, if any?
first out of 3 PR for #2698 

-Volunteers Table is now able to persist column visibility settings.
### What changed, and why?
After all 3 PR's are merged, the volunteers table will be able to persist column visibility settings.

This (1/3) PR adds a callback to ensure that all new users have a preference_set associated to it
This PR will also add a migration that adds a new column table_state to the preference_set table

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by GALTdea** [comment]
@dpaola2 there is 1 test failing and I am pretty sure it is an intermittent failure. What would be the best next steps (written by Daniel)

**Comment by dpaola2** [comment]
I would say try to push an empty commit. If it's intermittent you should be able to make it pass at some point.

**Comment by GALTdea** [comment]
> I would say try to push an empty commit. If it's intermittent you should be able to make it pass at some point.

**Comment by GALTdea** [comment]
hmm how was this pr closed?

**Review by compwron — APPROVED** [review]

**Pull request merged**
