### PR TITLE
3124 use occurred at date in reimbursement queue headers

### LINKED ISSUE #3124: Change Reimbursement Queue Date Added Column to Date Attempted
**What type(s) of user does this feature affect?**
 - admins

**Description**
Currently in the reimbursement queue there is a column for Date Added, which tells the admin the date that the case contact was added to the system. We would like to change this column to Date Attempted letting the admin know the date that the contact in question was attempted. 

**Screenshots of current behavior, if any**  
Reimbursement Queue

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by spotswoodb**
### What github issue is this PR for, if any?
Resolves #3124

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Screenshots please :)
Screen Shot 2022-02-19 at 2 18 05 PM

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Review by compwron — COMMENTED** [review]
This is looking good! Hopefully a test somewhere will be affected by this change :)

**Review by compwron — APPROVED** [review]
I added the missing translation. The date tests for this page pass because they are insufficiently specific

**Comment by spotswoodb** [comment]
Great, thank you! Working through the testing.

Any tips for writing correct tests?

**Comment by compwron** [comment]
A good test will fail if you take out the new code 
finding a test can be hard- if you have trouble finding it, it may not exist!

**Comment by compwron** [comment]
:) :) :)

**Pull request merged**
