### PR TITLE
Issue #2884, #2885: Add/Update Address Field used for mileage reimbursement

### LINKED ISSUE #2884: When Driving Reimbursement is Requested Require an Address
**What type(s) of user does this feature affect?**
 - volunteers
 - admins

**Description**
Currently we don't have any way of tracking volunteer addresses for mileage reimbursement. We would like to make it so that for CASAs with mileage reimbursement turned on, when Want Driving Reimbursement is set to yes in a Case Contact, an additional field will become visible and required that requests the volunteers address. Once this address has been set once it should auto-populate in the future, but continue to be editable. 

Related ticket: https://github.com/rubyforgood/casa/issues/2885

**Screenshots of current behavior, if any**  
Want Driving Reimbursement

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### LINKED ISSUE #2885: Add an Address Field to Editing Volunteer Page for CASAs that Use Mileage Reimbursement
**What type(s) of user does this feature affect?**
 - volunteers

**Description**
Currently we don't have any way of tracking volunteer addresses for mileage reimbursement. We would like to make it so that for CASAs with mileage reimbursement turned on, the Editing Volunteer Page has a field labeled Address for Mileage Reimbursement, where an address can be set that would be used to auto-populate the address request field on Case Contacts. (See ticket: https://github.com/rubyforgood/casa/issues/2884)

**Screenshots of current behavior, if any**  
Editting Volunteer Page

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by mussajoop**
### What github issue is this PR for, if any?
Resolves #2885
Resolves #2884 

### What changed, and why?
We add an Address Field to:
- Editing Volunteer Page for CASAs that Use Mileage Reimbursement
- new case contact page
- edit case contact page

### How will this affect user permissions?
- Volunteer permissions: n/a
- Supervisor permissions: n/a
- Admin permissions: n/a

### How is this tested? (please write tests!) 💖💪
- We are using system tests, to test all use cases
- Address field is present when mileage reimbursement is turned on on a Casa 
- if current user is an admin and case have more than one volunteer, a message is show _"There are two volunteers assigned to this case and you are trying to set the address for both of them. This is not currently possible."_
- if current user is an admin and case has one volunteer assigned, the volunteer address is updated/created
-  if current user is a volunteer, his address is used as an address for mileage reimbursement
- Previous tests affected by these changes have been updated

### Screenshots please :)
image
image

### CODE REVIEW

**Comment by compwron** [comment]
How is it going?

**Comment by mussajoop** [comment]
> How is it going? 

Pretty good! Just been a little bit busy lately. But I had already done the issue 2885. I'll work on #2884 tonight and hopefully link it to this PR

**Comment by compwron** [comment]
How is it going? I am excited to merge this when the tests are green! :)

**Comment by mussajoop** [comment]
> How is it going? I am excited to merge this when the tests are green! :)

The feature is implemented. Just have to write tests and It should be good to go! :)

**Pull request merged**
