### PR TITLE
List sent emails

### LINKED ISSUE #2011: Show casa admin a list of all emails we send
**What type of user is this for? volunteer/supervisor/admin/all**
admin

**Description**
Show casa admin a list of all emails we send 
On the casa org page
If it's easier, show types of emails rather than exact individual emails and recipients

**Screenshots of current behavior, if any**
https://casa-qa.herokuapp.com/casa_orgs/28/edit
CASA_Volunteer_Tracking

_QA Login Details:_
url: https://casa-qa.herokuapp.com/
password for all users: 123456

Log in using any of the below emails, depending on the account type you'd like to log in as.
- casa_admin1@example.com

### PR DESCRIPTION
**Pull request by aedwardg**
### What github issue is this PR for, if any?
Resolves #2011 

For now, I've left all my commits, but I can squash them at the end if need be.

### What changed, and why?
- Created SentEmail model to store emails sent by the app in the db
- Created event hook that saves all emails in the database when they are created (excluding emails sent to the All Casa Admin role)
- Displays 10 most recent emails to that org's members in the Edit Casa Org page (viewable by Casa Admin)

### How will this affect user permissions?
- Volunteer permissions: N/A
- Supervisor permissions: N/A
- Admin permissions: N/A

### How is this tested? (please write tests!) 💖💪
This is still a WIP, will write tests before finalizing.

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### CODE REVIEW

**Comment by compwron** [comment]
It's looking good! You still have it marked as draft, just lmk when you want review :)

**Comment by aedwardg** [comment]
> 
> 
> It's looking good! You still have it marked as draft, just lmk when you want review :)

I'm about ready for a review, I just need to add some tests for the Sent Email creation.  As of yet though, I haven't been able to figure out how/where it would be best to test this.

The Sent Email creation is triggered by an `ActiveSupport::Notifications` subscription in `config/initializers/sent_email_event.rb` so it's not immediately clear to me where these tests should go and how they should be designed.  If you have any suggestions, I'd love to hear them!

**Comment by compwron** [comment]
This looks like a solid collection of tests- I think you're just missing one for `config/initializers/sent_email_event.rb` which would go in `spec/config/initializers/sent_email_event_spec.rb` 
You can test a subscribe in one of several ways
https://stackoverflow.com/questions/7178670/testing-activesupportnotifications-with-rspec
https://stackoverflow.com/questions/54411184/how-to-spy-just-one-call-of-activesupportnotifications-instrument-not-all-of
https://stackoverflow.com/questions/32792075/rspec-testing-to-make-sure-notification-email-is-not-sent-after-invalid-recor
https://stackoverflow.com/questions/2063438/rails-how-do-you-test-actionmailer-sent-a-specific-email-in-tests
https://github.com/rails/rails/blob/main/activesupport/test/notifications_test.rb

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
Let's get this merged! I would like to see additional tests as discussed above in a later PR :)

**Pull request merged**
