### PR TITLE
New workflow to unassign inactive issues.

### LINKED ISSUE #1409: Automate github issue weekly "is this still in progress?" checkins
Automate github issue weekly "is this still in progress?" checkins on "in progress" github issues without recent comments / commits. After two weeks (14 days) of checking-in and no comments or PRs, unassign the assignee and move the issue back to "to do" (automate as many parts of this as possible! Anything is better than nothing :) )

This is (hopefully) possible with github actions

### PR DESCRIPTION
**Pull request by bjthompson805**
The workflow will run once per hour and will post a warning message in
issues that are older than 5 days telling the user that the issue will
be unassigned after 7 days. After 7 days it will be unassigned. The
algorithm to determine the time of inactivity will account for comments
made but not events.

### What github issue is this PR for, if any?
Resolves #1409

### What changed, and why?
A new workflow file was created in order to unassign inactive issues.

### How will this affect user permissions?
- Volunteer permissions: N/A
- Supervisor permissions: N/A
- Admin permissions: N/A

### How is this tested? (please write tests!) 💖💪
I tested it manually in a test harness I created:

https://github.com/bjthompson805/hello-world-javascript-action

### Screenshots please :)
Here is what it looks like when the bot comments as well as unassigns the issue.
image

### Other comments
I suggest a code review of the action itself as well:

https://github.com/bjthompson805/unassign-issues

Also, you may want to fork this action and use it under the rubyforgood repo owner so it's not attached to my name. Let me know and I'll change the workflow file to use it.

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
alt text

### CODE REVIEW

**Comment by compwron** [comment]
Very cool! I will dig into this more tomorrow + over the holiday break :) 
If it runs once per hour, that could be a LOT of messages - maybe we should make it once a day or something (or maybe I'm not completely caught up yet... )
This looks super cool! 🙌🎉✨

**Comment by bjthompson805** [comment]
> Very cool! I will dig into this more tomorrow + over the holiday break :)
> If it runs once per hour, that could be a LOT of messages - maybe we should make it once a day or something (or maybe I'm not completely caught up yet... )
> This looks super cool! 🙌🎉✨

Yeah I just realized that's true. I'll probably change the action so it doesn't post a new comment if the last one is from the bot.

**Comment by bjthompson805** [comment]
Fixed the issue of comment spams, and another issue where if there were only bot comments, it would unassign the issue.

**Review by compwron — APPROVED** [review]
It looks great! This is so cool :) 

Eventually we will probably want to customize the comment somehow with instructions for what to do i.e. "make a comment to reset the clock" and add some nice language like "thanks so much! Please feel free to pick up more CASA work when you have time!" etc. :)

**Comment by bjthompson805** [comment]
Looking back at my decision to ignore events... I think the action should look at some of them, at least. E.g. #1405 was unassigned even though it was recently self-assigned because there were no recent comments. It should not unassign it if it was recently assigned.

I think that might be the only event I should account for.

It should also comment before it unassigns it, explaining why.

**Comment by bjthompson805** [comment]
I've fixed the issue where it unassigns even after a recently assigned issue. Also added a notification message to explain the unassign (see below).

It also was only checking the first 25 issues. The max to check is 100 so I've set it to that (I don't imagine we would ever need to check more the 100 most recent issues, but if we do we can implement pagination through the data and get the entire array of open issues).

I looked thru the 25 issues and did not notice the bot doing anything else that it shouldn't. Let me know if you notice anything else that is wrong.

New comment that is made during unassignment:
image

**Pull request merged**
