### PR TITLE
added trait follow up for notification factory

### LINKED ISSUE #4258: Create a trait for a "FollowupNotification" in the notification factory
Add a factorybot trait to `spec/factories/notifications.rb` to our notifications factory that makes the notification into a `FollowupNotification`  
see: [main/spec/factories/notifications.rb](https://github.com/rubyforgood/casa/blob/main/spec/factories/notifications.rb)
see: https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by ShamiTomita**
### What github issue is this PR for, if any?
Resolves #4258

### What changed, and why?
Added trait to the notifcation factory for the FollowupNotification type

### How will this affect user permissions?
- Volunteer permissions: none
- Supervisor permissions: none 
- Admin permissions: none

### How is this tested? (please write tests!) 💖💪
No associated test yet

### Screenshots please :)
No UI changes

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Review by ShamiTomita — COMMENTED** [review]
Hi, I was looking for associated tests in the suite but I couldn't find "Followup Notification" being used.

**Comment by FireLemons** [comment]
> Hi, I was looking for associated tests in the suite but I couldn't find "Followup Notification" being used.
Well this is because we need the factory to create a followup notification for tests

**Comment by FireLemons** [comment]
A followup notification is more than just the type. You'll have to create an object more like this.

image
```
[#<Notification:0x00007f154c8f0968                                       
  id: 1,                                                                 
  recipient_type: "User",                                                
  recipient_id: 6,                                                       
  type: "FollowupNotification",                                          
  params:                                                                
   {:followup=>                                                          
     #<Followup:0x00007f154c80ebd0                                       
      id: 1,                                                             
      case_contact_id: 9,                                                
      creator_id: 1,                                                     
      status: "resolved",
      created_at: Wed, 07 Dec 2022 03:33:30.637672000 UTC +00:00,
      updated_at: Fri, 09 Dec 2022 17:41:28.092957000 UTC +00:00,
      note: "dfdsafsadfdsafdsa">,
    :created_by=>
     #<CasaAdmin id: 1, email: "casa_admin1@example.com", created_at: "2022-11-24 02:45:44.872432000 +0000", updated_at: "2022-12-09 22:10:47.223902000 +0000", casa_org_id: 1, display_name: "Alisia Hodkiewicz", active: true, phone_number: "+16306141182", receive_sms_notifications: false, receive_email_notifications: true>},
  read_at: nil,
  created_at: Wed, 07 Dec 2022 03:33:30.963702000 UTC +00:00,
  updated_at: Wed, 07 Dec 2022 03:33:30.963702000 UTC +00:00>]
```

**Comment by zorab47** [comment]
@ShamiTomita we'll have to include the specific params as well.

@FireLemons is there a test scenario that would benefit from this factory? It would help inform what the factory should populate in the database. Having the `params` attribute hold a followup object wasn't clear from the original issue, and that is helpful feedback.

**Comment by FireLemons** [comment]
> Is there a test scenario that would benefit from this factory?
The factory is for making test data. We don't have any tests for notifications with notes because we don't have a factory for that.

I don't know how exactly followup notifications are made. Somewhere in the app details how. Just replicate that in the factory

**Comment by ShamiTomita** [comment]
@FireLemons Hi again, so I've been working on this as well as trying to understand how to use FactoryBot. I've been able to find how Followup Notifications are made and although I still need to figure out how to include an actual copy of Followup and Supervisor within the trait itself, I wanted to ask if this is a little closer to what the final solution could look like? Thank you! 
Screen Shot 2022-12-12 at 7 09 15 PM
Screen Shot 2022-12-12 at 7 09 33 PM

**Comment by ShamiTomita** [comment]
Screen Shot 2022-12-13 at 10 38 05 AM
@FireLemons  Good Morning! We were able to set up the :followup trait with a proper params hash with a followup record and creator(user) record

**Comment by zorab47** [comment]
@ShamiTomita did intend to close this pull request?

**Pull request closed without merging**
