### PR TITLE
All casa admins can edit a patch note

### PR DESCRIPTION
**Pull request by FireLemons**
### What github issue is this PR for, if any?
Related to ##3651

### What changed, and why?
Added ability to edit a patch note

### How is this tested? (please write tests!) 💖💪
Manually

### Screenshots please :)
Screenshots don't really show whether editing works or not

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Review by compwron — APPROVED** [review]

**Comment by FireLemons** [comment]
Codeclimate is right. I gotta break those UI modifying functions down into smaller functions

**Comment by FireLemons** [comment]
@compwron can you merge this one so it counts for hacktoberfest?

**Comment by FireLemons** [comment]
@littleforest @Thrillberg could one of you merge this? I'm pretty sure it won't count for hacktoberfest if I merge my own pr.

**Comment by compwron** [comment]
I merged it
I think it does count based on some PRs I made earlier

**Comment by compwron** [comment]
Screen Shot 2022-10-21 at 12 16 55 PM

**Pull request merged**
