### PR TITLE
Add helper method to show only volunteers not already assigned to the…

### LINKED ISSUE #1242: Assign a New Volunteer dropdown contains already assigned volunteers
**What is the problem, and what should happen instead?**
On the Edit Cases page, volunteers still appear in the 'Assign a New Volunteer' dropdown list even after they've been assigned to a case (screenshot no. 1). The user can click their names and nothing happens, as they're already assigned. This is particularly confusing when the case only has a few volunteers - in this case the dropdown completely covers the names of currently assigned volunteers (screenshot no. 2).

**Reproduction steps:**
Go to Cases, pick a case and click Edit
If no volunteers are assigned, assign one using the dropdown at the bottom
Notice that the names of volunteers who have already been assigned appear in the dropdown list

**Screenshots of current behavior, if any**
Screenshot 2020-11-04 at 20 01 29

Screenshot 2020-11-04 at 20 07 34

### PR DESCRIPTION
**Pull request by cjilbert504**
… current casa case being edited as able to be assigned to the case

### What github issue is this PR for, if any?
Resolves #1242 

### What changed, and why?
Added a helper method to only show volunteers who are not already assigned to the current casa case in the dropdown for assigning a new volunteer.

### How will this affect user permissions?
- Volunteer permissions: none
- Supervisor permissions: none
- Admin permissions: none

### How is this tested? (please write tests!) 💖💪
There is a pending spec but I'm not sure how to implement the test and would love help with figuring it out. I tried a bunch of things and searched around on the web for solutions but came up with nothing.

### Screenshots please :)
image
image

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### CODE REVIEW

**Comment by cjilbert504** [comment]
Doh! I forgot to run the linters.

**Comment by cjilbert504** [comment]
hmmm let me look into the failure here

**Comment by scottolsen** [comment]
@cjilbert504 I'd be happy to pair with you on this. I've got an idea for a regression test and I think I know why `/spec/system/casa_cases/edit_spec.rb:256` is failing.

**Comment by cjilbert504** [comment]
@scottolsen that sounds great! Let me know what your availability is like and we can hop on this together.

**Comment by scottolsen** [comment]
@cjilbert504 I have about 30ish minutes right now or sometime after 6pm tonight. I'm in Central Timezone.

**Comment by cjilbert504** [comment]
@scottolsen Hey! Sorry I couldn't make it today but tomorrow or Wednesday look pretty open for me. Let me know how you look for those. Oh, I'm on central time as well. 😀

**Comment by scottolsen** [comment]
@cjilbert504 I'm pretty open today except for between 11:30am and 1:30pm.

**Comment by cjilbert504** [comment]
@scottolsen ok I should be free after about 3:00pm. So how’s 3:30 just to be safe?

**Comment by scottolsen** [comment]
@cjilbert504 3:30 works for me!

**Comment by cjilbert504** [comment]
@scottolsen Righteous

**Review by compwron — APPROVED** [review]
🙌💖💪

**Pull request merged**
