### PR TITLE
[WIP] Refactor: Remove transition_aged_youth from casa_cases

### LINKED ISSUE #2145: refactor: remove transition_aged_youth and only use casa_case.birth_month_year_youth
refactor: remove all usages of `casa_case.transition_aged_youth` and only use `casa_case.birth_month_year_youth` and also make a migration to remove `casa_case.transition_aged_youth`. Make sure to use "Rails Ignored Columns".

We want to do this because having two different flags for this is having extra state which is unnecessary. 

Also remove this rake task
and the heroku job that runs it in qa, staging, and prod. 
```
desc "Transition youth who are now 14, run by heroku scheduler"
task transition_youth: :environment do
  puts "Updating casa cases..."
  CasaCase.should_transition.update_all(transition_aged_youth: true)
  puts "done."
end
```

### PR DESCRIPTION
**Pull request by hiendinhngoc**
### What github issue is this PR for, if any?
Resolves #2145

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### CODE REVIEW

**Review by compwron — COMMENTED** [review]
I am excited for this PR! You have some merge conflicts. I am happy to help with them, or feel free to ask in slack #casa channel if you want advice or a pair :)

**Comment by hiendinhngoc** [comment]
> I am excited for this PR! You have some merge conflicts. I am happy to help with them, or feel free to ask in slack #casa channel if you want advice or a pair :)

Thank you. I am currently fixing some failed tests. I guess the failures were due to the changes I made when deleting some things related to `transition_aged_youth`.

**Comment by compwron** [comment]
This is exciting! Let's be very careful with the deploy on this one...

**Comment by compwron** [comment]
We will try again soon :)

**Pull request closed without merging**
