### PR TITLE
2771 Add reimbursement queue filters

### LINKED ISSUE #2771: Add Filters to Reimbursement Queue View
**What type(s) of user does this feature affect?**
 - admins

**Description**
As an Admin, I would like to be able to filter paid and unpaid  reimbursements by volunteer, expense type, and date added so that I can see reimbursements by each filter category.

**How should it work**
- Filters should be displayed as outlined in mock-up
   - https://www.figma.com/proto/HBcfH4G9W2pD8psX67orhg/CASA-Redesigns?page-id=30%3A267&node-id=32%3A2&viewport=345%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=67%3A202&show-proto-sidebar=1

**Acceptance Criteria**
- Results on page should display selected filter options
- Total at bottom of page updates to the correct amount of all amounts added from selected filter options
- Filters don't break other functionality of page

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by lukenofurther**
### What github issue is this PR for, if any?
Resolves #2771

### CODE REVIEW

**Comment by compwron** [comment]
This looks exciting! I see it's in draft status. How's it going? Can I help?

**Comment by lukenofurther** [comment]
@compwron thanks for asking. The rewrite of the reimbursement view as a data table is nearly there, then adding the new filters on shouldn't be too much more work. My main issue is finding time to work on it! Tonight's the first time since before the holiday season.

There is one thing that's puzzling me. There are unrelated specs failing in the PR staging build (e.g. `./spec/system/supervisors/edit_spec.rb`). I have a tinkling it's because I added the url_helper to `reimbursement_datatable_spec.rb`. Might that be causing these failures and if not, do you know what else it could be?

Also, is it okay that I opened a draft PR like this?

**Comment by compwron** [comment]
Yes, draft PRs are great :)

**Comment by compwron** [comment]
It's looking good! Some sort issues is my guess at the cause of the CI failure

```
rspec ./spec/views/reimbursements/index.html.erb_spec.rb:10 # reimbursements/index should not have any translation missing classes
rspec './spec/datatables/reimbursement_datatable_spec.rb[1:2:5:1:1]' # ReimbursementDatatable multiple record handling order by case number behaves like a sorted results set should order ascending by default
rspec './spec/datatables/reimbursement_datatable_spec.rb[1:2:5:1:3:1]' # ReimbursementDatatable multiple record handling order by case number behaves like a sorted results set descending order should order correctly
rspec './spec/datatables/reimbursement_datatable_spec.rb[1:2:5:1:2:1]' # ReimbursementDatatable multiple record handling order by case number behaves like a sorted results set explicit ascending order should order correctly
```

**Comment by compwron** [comment]
Let me know if I can help in any way here :)

**Comment by compwron** [comment]
It looks like the main part left is the TODO around being able to complete reimbursement functionality. We do need to keep that. :) Will you be able to get back to this? :) @[lukenofurther](https://github.com/lukenofurther)

**Comment by compwron** [comment]
:)

**Pull request merged**
