### PR TITLE
Change casa_org resource to singular

### LINKED ISSUE #2919: /casa_org should be a singular resource path
Right now, the casa_orgs path is a plural resource:

`resources :casa_orgs, only: %i[edit update]
`

But the controller ignores the id:

```
  def set_casa_org
    @casa_org = current_organization
  rescue ActiveRecord::RecordNotFound
    head :not_found
  end
```
This is a singular resource and should be treated as such.

This will change some specs and some path helpers in views.

### PR DESCRIPTION
**Pull request by efgalvao**
### What github issue is this PR for, if any?
Resolves #2919 

### What changed, and why?
Change the resource casa_org to singular, it was necessary to do some fixes.

### How will this affect user permissions?
It will not.

### How is this tested? (please write tests!) 💖💪
The tests are fixed and still passing 😆 

### Screenshots please :)
Just some code changes, nothing visual.

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
efgalvao

### CODE REVIEW

**Review by compwron — APPROVED** [review]
:)

**Comment by compwron** [comment]
Looks great! Feel free to merge when the merge conflicts are resolved :)

**Comment by efgalvao** [comment]
@compwron , these errors in rspec, i think there is no connection with my changes, can you give a look ?

**Comment by mdchaney** [comment]
This is not correct - please do not merge.

This should only affect /casa_org, which is the path used by a casa administrator.  Looking at the code, the path in /all_casa_admins was also changed to a singular, which is not correct.  That path needs access to all of the casa_orgs.

**Comment by compwron** [comment]
Correct, the test errors come from a change in a different PR which I was hoping to merge-and-fix last night but we did not quite get there. Sorry for the confusion :(

**Comment by efgalvao** [comment]
All right, can you give me a word when it is fixed so I rebase my branch, while this I will revert the changes in the all_casa_admins/casa_orgs.

**Comment by compwron** [comment]
Will do

**Comment by compwron** [comment]
@efgalvao CI is fixed, you can rebase :)

**Review by compwron — APPROVED** [review]

**Comment by mdchaney** [comment]
Arg, my comment should be “not”, not “now”.  Those files won’t affect anything since the changes are in comments, but they’re not correct.  I will push out a change to revert them.

**Pull request merged**
