### PR TITLE
800 Add “birth month and year” column header to example case csv file

### PR DESCRIPTION
**Pull request by stevelandwehr**
### What github issue is this PR for, if any?
https://github.com/rubyforgood/casa/issues/800

### What changed, and why?
Added a "birth month and year" column header to the example case csv file.

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Screenshots please :)
image

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### CODE REVIEW

**Review by drborges — APPROVED** [review]
LGTM

**Comment by casadei** [comment]
Can we update the column header to be `birth_month_year_youth`? That way it will be compatible with the changes present in [this PR](https://github.com/rubyforgood/casa/pull/847).

**Comment by stevelandwehr** [comment]
> Can we update the column header to be `birth_month_year_youth`? That way it will be compatible with the changes present in [this PR](https://github.com/rubyforgood/casa/pull/847).

Yep! I'll make that change right now.

**Comment by casadei** [comment]
> > Can we update the column header to be `birth_month_year_youth`? That way it will be compatible with the changes present in [this PR](https://github.com/rubyforgood/casa/pull/847).
> 
> Yep! I'll make that change right now.

Awesome! I've updated the tests of my PR to use the same date pattern that you guys used in this example file! Thank you.

**Review by casadei — APPROVED** [review]

**Comment by compwron** [comment]
You are invited to the CASA asynchronous retrospective-and-futurespective! Please take a look at https://bit.ly/casaretro (no login required) and add at least one note! Even if it's just "I was here and you are cool" or "omg y'all why do you keep messaging me" we want to hear it. <3
Next week Wednesday 18 November @ 6pm Pacific time we will Zoom about the board and talk about themes and takeaways. (Zoom link link in slack #casa channel https://rubyforgood.herokuapp.com/ )
Please ESPECIALLY add lots of notes if you won't be able to make it on Wednesday to talk!
* Note: the board will be monitored for spam; message me or any team lead if you see a problem
https://bit.ly/casaretro

**Pull request merged**
