### PR TITLE
Resolves #3112 - Move volunteer management to a partial

### LINKED ISSUE #3112: Create partial for Manage Volunteers section
Create partial for Manage Volunteers section 
So we can get re-use and DRY code
image (2)
image (1)

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by mattwd7**
### What github issue is this PR for, if any?
Resolves #3112

### What changed, and why?
Duplicate view logic was moved to a partial to DRY up the code.

### How will this affect user permissions?
n/a

### How is this tested? (please write tests!) 💖💪
Covered by existing tests

### Outstanding questions:
*I'm curious how much of an improvement this is... y'all let me know what you think before I continue forward!**

### CODE REVIEW

**Review by compwron — APPROVED** [review]
Yay!!!

**Comment by compwron** [comment]
@[mattwd7](https://github.com/mattwd7) I like this approach, please continue :)

**Comment by compwron** [comment]
@[mattwd7](https://github.com/mattwd7) how's it going? :)

**Comment by mattwd7** [comment]
I need to fix specs when I find more time to contribute. If someone wants to take over what I've started, they are welcome :)

**Comment by compwron** [comment]
```
rspec ./spec/views/supervisors/edit.html.erb_spec.rb:24 # supervisors/edit does not display the 'Unassign' button next to volunteer no longer supervised by the supervisor
rspec ./spec/system/supervisors/edit_spec.rb:39 # supervisors/edit logged in as an admin can go to the supervisor edit page and see red message when there are no active volunteers
rspec ./spec/system/supervisors/edit_spec.rb:232 # supervisors/edit logged in as a supervisor when editing own page when there are assigned volunteers shows assigned volunteers
rspec ./spec/system/supervisors/edit_spec.rb:246 # supervisors/edit logged in as a supervisor when editing own page when there are assigned volunteers when there are previously unassigned volunteers does not show them by default
rspec ./spec/system/supervisors/edit_spec.rb:221 # supervisors/edit logged in as a supervisor when editing own page when no volunteers exist does not error out when adding non-existent volunteer
rspec ./spec/system/supervisors/edit_spec.rb:268 # supervisors/edit logged in as a supervisor when editing own page when there are no currently assigned volunteers and there are previously unassigned volunteers does not show them by default
rspec ./spec/system/supervisors/edit_spec.rb:191 # supervisors/edit logged in as a supervisor when editing other supervisor sees red message when there are no active volunteers
```

**Comment by compwron** [comment]
We did not get to this in office hours but I hope to get this merged soon!

**Comment by compwron** [comment]
We did not get this merged this week... I still want to tho! It should only take a little work 😅

**Comment by compwron** [comment]
I do still want to get this merged. maybe at office hours this week :)

**Pull request closed without merging**
