### PR TITLE
Fixes #2953 Adds new decorator method to dispay formatted date and he…

### LINKED ISSUE #2953: Add Hearing Type to Past Court Date List
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Currently we just show past court dates on our list of court dates. We would like to also show what type of hearing each court date was. 

**Screenshots of current behavior, if any**  
You can paste images on the clipboard here

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by cjilbert504**
…aring type

### What github issue is this PR for, if any?
Resolves #2953

### What changed, and why?
Added the desired rendering of the hearing type of past court dates.

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:
All can see the hearing types associated to a past court date.

### How is this tested? (please write tests!) 💖💪
CleanShot 2021-11-17 at 22 09 44

### Screenshots please :)
CleanShot 2021-11-17 at 22 10 15

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
Looks good, just needs some conflicts resolved :) This approach is my fave

**Comment by cjilbert504** [comment]
@compwron - lol and what approach are you referring to here? Simplistic? lol

**Comment by compwron** [comment]
Merge conflictssss

**Comment by cjilbert504** [comment]
Gonna fix these tonight.

**Comment by compwron** [comment]
Failing tests
```
      # NoMethodError:
      #   undefined method `name' for nil:NilClass
      #   ./app/decorators/court_date_decorator.rb:9:in `formatted_date_with_hearing_type_name'
```

**Comment by compwron** [comment]
I blame dates

```

  4) Edit CASA Case logged in as supervisor behaves like shows court dates links past court dates are ordered
     Failure/Error: expect(page).to have_text((DateTime.current - 10.days).strftime("%B %-d, %Y").to_s)
       expected to find text "November 29, 2021" in "Please enable javascript\nThis app requires javascript to work\nMenu\nInbox Supervisors Volunteers Cases\nLocation CASA Org 23 Role Supervisor\nEdit Profile Generate Court Reports Export Data Report a site issue Leia Fritsch email24@example.com Log out\n🦋 CASA Case Details\nNew Case Contact Edit Case Details\nGenerate Report ⏳\nCase number: CINA-42\nHearing Type: Emergency Hearing 49\nJudge: Claretta O'Connell\nTransition Aged Youth: Yes 🦋\nNext Court Date:\nCourt Report Due Date:\nCourt Report Status: Not submitted\nCourt Orders:\n✅ Depulso undique maiores. Turbo clementia tricesimus. Beatus abundans denego. Inflammatio vociferor vobis. Deduco tui casus. Ab comparo atqui. Illo cui iste. Ademptio aut iste. Arx aestus sol. Copia torqueo armarium. Suggero adicio quia. Despirmatio sui demum. Accipio at infit. Spiculum vitium aufero. Accommodo absens sit. Theologus angelus vita. Molestiae rerum culpa. Tonsor consequatur tracto.\n❌ Autem cibo umquam. Summa stabilis sollers. Demonstro caritas speculum. Tui comitatus voluptatem. Vultuosus unde coniuratio. Vulpes dens beatae. Animi cernuus tremo. Aut pax verecundia. Calculus admiratio ancilla. Ventito torqueo supellex. Despecto aegrotatio nesciunt. Crustulum acerbitas tenax. Vinum triumphus exercitationem. Voluptatem patria coadunatio.\nCourt dates:\n/casa_cases/72/court_dates/95\nDecember 2, 2021 - Emergency Hearing 51\n/casa_cases/72/court_dates/97\n/casa_cases/72/court_dates/94\nAdd a court date\nAssigned Volunteers:"
     Shared Example Group: "shows court dates links" called from ./spec/system/casa_cases/edit_spec.rb:96
     # ./spec/support/shared_examples/shows_court_dates_links.rb:34:in `block (2 levels) in <main>'

Finished in 44.52 seconds (files took 2.67 seconds to load)
33 examples, 4 failures

Failed examples:

rspec ./spec/system/casa_cases/edit_spec.rb:484 # Edit CASA Case logged in as volunteer views attached court reports
rspec './spec/system/casa_cases/edit_spec.rb[1:3:1:2]' # Edit CASA Case logged in as volunteer behaves like shows court dates links past court dates are ordered
rspec './spec/system/casa_cases/edit_spec.rb[1:1:1:2]' # Edit CASA Case logged in as admin behaves like shows court dates links past court dates are ordered
rspec './spec/system/casa_cases/edit_spec.rb[1:2:1:2]' # Edit CASA Case logged in as supervisor behaves like shows court dates links past court dates are ordered
```

**Comment by compwron** [comment]
<3

**Pull request closed without merging**
