### PR TITLE
Refactor court_dates_controller_specs to request specs

### PR DESCRIPTION
**Pull request by LeGorge**
### What github issue is this PR for, if any?
Part of #4129
Not closing yet as there will be more on the way.

### What changed, and why?
The court_dates_controller_spec file was removed and its specs moved to court_dates_spec.
Notes:

 - Different authorization contexts present in the controller test were not being tested in `court_date_policy_spec` so I added them there also.
 - Added a couple of missing expectations to the logic present in the endpoint as well.

### How will this affect user permissions?
- no effect

### How is this tested? (please write tests!) 💖💪
- does not apply

### Screenshots please :)
- does not apply

### Feedback please? (optional)
The destroy action for court dates controller is allowed to any supervisor or admin, not just the ones from the same org as the case. All the other actions follow a different rule (checking for same org as the case).
I found that a bit odd, maybe it's by design, but it doesn't hurt to point it out.

### CODE REVIEW

**Comment by compwron** [comment]
master CI is broken right now, this PR is ok to merge but I want master green first.

**Review by compwron — APPROVED** [review]

**Comment by LeGorge** [comment]
Seems like a flickering spec. I guess I can't rerun it.

**Comment by anshu1992** [comment]
It's a lint error. It can be fixed by running `bundle exec standardrb --fix` on your local.

**Comment by LeGorge** [comment]
@anshu1992 The flickering test I mentioned was from a previous run.

That lint problem is not from the files I changed.

**Comment by anshu1992** [comment]
Ah, okay, my bad!

**Comment by compwron** [comment]
:)

**Pull request merged**
